import { execFile } from 'node:child_process'
import { access, readFile } from 'node:fs/promises'
import { join, posix } from 'node:path'
import { promisify } from 'node:util'

import type { SourceProfile } from './config.js'

const execFileAsync = promisify(execFile)

const SOURCE_EXTENSION = /\.(?:[cm]?[jt]sx?|[cm]ts)$/
const DECLARATION_FILE = /\.d\.(?:[cm]?ts)$/
const GENERATED_FILE = /(?:^|\/)[^/]+\.(?:generated|gen)\.[^/]+$/
const EXCLUDED_SEGMENTS = new Set([
  'build',
  'coverage',
  'dist',
  'generated',
  'node_modules',
  'prebuilds',
  'third-party',
  'vendor',
])

export async function discoverSourceFiles(root: string): Promise<readonly string[]> {
  const { stdout } = await execFileAsync(
    'git',
    ['ls-files', '-co', '--exclude-standard', '-z'],
    { cwd: root, encoding: 'buffer', maxBuffer: 100 * 1024 * 1024 },
  )

  const candidates = stdout
    .toString('utf8')
    .split('\u0000')
    .filter(isSourceFile)
    .sort((left, right) => left.localeCompare(right, 'en'))
  const packageRootByDirectory = new Map<string, string | undefined>()
  const sources: string[] = []

  for (const path of candidates) {
    if (await hasGeneratedHeader(root, path)) {
      continue
    }
    if (await isCompiledMirror(root, path, packageRootByDirectory)) {
      continue
    }
    sources.push(path)
  }

  return sources
}

export function classifySourceFile(path: string): SourceProfile {
  const normalized = path.replaceAll('\\', '/').toLowerCase()
  const segments = normalized.split('/')
  const filename = segments.at(-1) ?? ''
  const isAuxiliary = segments.some((segment) => {
    return [
      '.github',
      '__tests__',
      'benchmark',
      'benchmarks',
      'example',
      'examples',
      'fixture',
      'fixtures',
      'script',
      'scripts',
      'test',
      'tests',
    ].includes(segment)
  }) || /(?:^|\.)+(?:config|test|spec)\.[^.]+$/.test(filename)

  return isAuxiliary ? 'auxiliary' : 'production'
}

function isSourceFile(path: string): boolean {
  const normalized = path.replaceAll('\\', '/')
  const segments = normalized.split('/')

  return SOURCE_EXTENSION.test(normalized)
    && !DECLARATION_FILE.test(normalized)
    && !GENERATED_FILE.test(normalized)
    && !segments.some((segment) => EXCLUDED_SEGMENTS.has(segment))
}

async function hasGeneratedHeader(root: string, path: string): Promise<boolean> {
  const header = (await readFile(join(root, path), 'utf8'))
    .slice(0, 2048)
    .split(/\r?\n/)
    .slice(0, 12)

  return header.some((line) => {
    return /^\s*(?:\/\/|\/\*|\*)/.test(line)
      && /(?:AUTO-GENERATED|AUTOGENERATED|@generated|DO NOT EDIT|DO NOT MODIFY MANUALLY)/i.test(line)
  })
}

async function isCompiledMirror(
  root: string,
  path: string,
  packageRootByDirectory: Map<string, string | undefined>,
): Promise<boolean> {
  const sourceExtensions = compiledSourceExtensions(path)
  if (sourceExtensions.length === 0) {
    return false
  }

  const packageRoot = await nearestPackageRoot(
    root,
    posix.dirname(path),
    packageRootByDirectory,
  )
  if (packageRoot === undefined) {
    return false
  }

  const relative = path.slice(packageRoot.length + 1)
  if (relative.startsWith('src/')) {
    return false
  }
  const stem = relative.replace(/\.[^.]+$/, '')

  for (const extension of sourceExtensions) {
    if (await fileExists(join(root, packageRoot, 'src', `${stem}${extension}`))) {
      return true
    }
  }
  return false
}

function compiledSourceExtensions(path: string): readonly string[] {
  if (path.endsWith('.jsx')) {
    return ['.tsx', '.ts']
  }
  if (path.endsWith('.mjs')) {
    return ['.mts', '.ts']
  }
  if (path.endsWith('.cjs')) {
    return ['.cts', '.ts']
  }
  if (path.endsWith('.js')) {
    return ['.ts', '.tsx']
  }
  return []
}

async function nearestPackageRoot(
  root: string,
  startDirectory: string,
  cache: Map<string, string | undefined>,
): Promise<string | undefined> {
  const visited: string[] = []
  let directory = startDirectory === '.' ? '' : startDirectory

  while (true) {
    if (cache.has(directory)) {
      const cached = cache.get(directory)
      for (const visitedDirectory of visited) {
        cache.set(visitedDirectory, cached)
      }
      return cached
    }

    visited.push(directory)
    if (
      directory !== ''
      && await fileExists(join(root, directory, 'package.json'))
    ) {
      for (const visitedDirectory of visited) {
        cache.set(visitedDirectory, directory)
      }
      return directory
    }
    if (directory === '') {
      for (const visitedDirectory of visited) {
        cache.set(visitedDirectory, undefined)
      }
      return undefined
    }
    const parent = posix.dirname(directory)
    directory = parent === '.' ? '' : parent
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}
