server:
  url: "http://localhost:8080/run"
  batch_size: 32
  lib: "@tetherto/qvac-lib-inference-addon-mlc-indictrans2-indic-indic-1b-q0f32"
  version: "1.3.3"
huggingface:
  token: "<hf-token>"
dataset:
  src_lang: "asm_Beng"
  dst_lang: "pan_Guru"
bleu:
  enabled: true
  smooth_method: "exp"
  lowercase: false
  tokenizer: "none"
  force_tokenize: false
  use_effective_order: false
comet:
  enabled: true
  xcomet: false
  batch_size: 2
  gpus: 1
