server:
  url: "http://localhost:8080/run"
  batch_size: 32
  model_id: "model.bin"
  hyperdrive_key: "68778c8375fbb1e7f5c20b4e6087131206e9ddba1872655e20931b7e08fe3954"
huggingface:
  token: <hf-token>
dataset:
  src_lang: "ita_Latn"
  dst_lang: "eng_Latn"
bleu:
  enabled: true
  smooth_method: "exp"
  lowercase: false
  tokenizer: "flores200"
  force_tokenize: false
  use_effective_order: false
comet:
  enabled: true
  xcomet: false
  batch_size: 2
  gpus: 1
