# Generated by scripts/generate.py. Do not edit by hand.
"""Numeric public vocabularies (name -> number) mirroring @qvac/sdk's
exported constants of the same name, via contract/numeric-constants.json.
"""

from __future__ import annotations

ASR_BACKEND_IDS: dict[str, int] = {
    "CPU": 0,
    "Metal": 1,
    "CUDA": 2,
    "Vulkan": 3,
    "OpenCL": 4,
    "Other": 99,
}

__all__ = [
    "ASR_BACKEND_IDS",
]
