# Generated by scripts/generate.py. Do not edit by hand.
"""The `@qvac/sdk` version this generated client matches; the worker it
connects to must be this version. Sourced from packages/sdk/package.json.
"""

from __future__ import annotations

SDK_VERSION = "0.15.0"

__all__ = ["SDK_VERSION"]
