#!/usr/bin/env bash
#
# .agent/setup.sh — Configure agent tooling for Claude Code and/or Cursor
#
# Usage: .agent/setup.sh [claude|cursor|all] [--force|--keep|--clean]
#
# Copies shared config from .agent/ into tool-specific directories at the git root.
# Checks for conflicts by default; use --force/--keep/--clean to resolve.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)" || {
  echo "ERROR: Not inside a git repository. setup.sh must be run from within a git repo."
  exit 1
}
SCRIPT_REL="${SCRIPT_DIR#$REPO_ROOT/}"

# Resolve agent root from config (paths.agentRoot); defaults to REPO_ROOT.
# All tool directories (.claude/, .cursor/, .agent-handoff/) are written under AGENT_ROOT.
AGENT_ROOT="$REPO_ROOT"
if [ -f "$SCRIPT_DIR/config.json" ]; then
  CUSTOM_ROOT="$(node -e "
    const c = require('$SCRIPT_DIR/config.json');
    if (c.paths && c.paths.agentRoot) process.stdout.write(c.paths.agentRoot);
  " 2>/dev/null)" || true
  if [ -n "$CUSTOM_ROOT" ]; then
    case "$CUSTOM_ROOT" in
      /*) AGENT_ROOT="$CUSTOM_ROOT" ;;
      *)
        echo "ERROR: paths.agentRoot must be an absolute path, got '$CUSTOM_ROOT'"
        exit 1
        ;;
    esac
  fi
fi

HANDOFF_DIR="$AGENT_ROOT/.agent-handoff"

HEADER="<!-- AUTO-GENERATED by .agent/setup.sh — do not edit directly. Edit the source in .agent/ instead. -->"

# ---------------------------------------------------------------------------
# Strategy and conflict tracking
# ---------------------------------------------------------------------------
STRATEGY=""
CONFLICT_COUNT=0
declare -a CONFLICT_FILES=()

# ---------------------------------------------------------------------------
# Core write function — routes all file writes through conflict detection
# ---------------------------------------------------------------------------
write_file() {
  local tmp="$1"
  local dst="$2"
  local rel="${dst#$AGENT_ROOT/}"

  mkdir -p "$(dirname "$dst")"

  if [ ! -f "$dst" ]; then
    cp "$tmp" "$dst"
    echo "  [N] $rel"
    return 0
  fi

  if diff -q "$tmp" "$dst" >/dev/null 2>&1; then
    echo "  [=] $rel (unchanged)"
    return 0
  fi

  case "$STRATEGY" in
    force|clean)
      cp "$tmp" "$dst"
      echo "  [U] $rel (updated)"
      ;;
    keep)
      echo "  [S] $rel (kept existing)"
      ;;
    "")
      CONFLICT_COUNT=$((CONFLICT_COUNT + 1))
      CONFLICT_FILES+=("$rel")
      echo "  [M] $rel (differs from source)"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
copy_with_header() {
  local src="$1"
  local dst="$2"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

copy_plain() {
  local src="$1"
  local dst="$2"
  local tmp
  tmp="$(mktemp)"
  cp "$src" "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

strip_yaml_frontmatter() {
  awk '
    BEGIN { in_front=0; found=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { in_front=0; found=1; next }
    in_front { next }
    found && NR>1 && /^\s*$/ && !printed { next }
    { printed=1; print }
  ' "$1"
}

wrap_with_frontmatter() {
  local src="$1"
  local name="$2"
  local description="$3"
  local dst="$4"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$description"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

wrap_mdc_rule() {
  local src="$1"
  local description="$2"
  local always_apply="$3"
  local dst="$4"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: %s\n---\n\n' "$description" "$always_apply"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

extract_frontmatter_field() {
  local file="$1"
  local field="$2"
  awk -v f="$field" '
    BEGIN { in_front=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { exit }
    in_front && $0 ~ "^"f":" {
      sub("^"f":[ ]*", "")
      gsub(/^"/, ""); gsub(/"$/, "")
      print
      exit
    }
  ' "$file"
}

generate_cursor_agent_rule() {
  local src="$1"
  local dst="$2"
  local agent_name
  agent_name="$(extract_frontmatter_field "$src" "name")"
  local description="Agent prompt: ${agent_name} — use as context when launching Task sub-agents"
  local body
  body="$(strip_yaml_frontmatter "$src")"

  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: false\n---\n\n' "$description"
    printf '%s\n' "$body" \
      | sed 's|`\.claude/agent-conduct\.md`|the agent conduct rules (`.cursor/rules/agent-conduct.mdc`)|g'
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

generate_handoff_skill() {
  local tool="$1"
  local src="$SCRIPT_DIR/skills/handoff/SKILL.md"
  local dst

  if [ "$tool" = "claude" ]; then
    dst="$AGENT_ROOT/.claude/skills/handoff/SKILL.md"
  elif [ "$tool" = "cursor" ]; then
    dst="$AGENT_ROOT/.cursor/skills/handoff/SKILL.md"
  else
    echo "  warning: generate_handoff_skill() — unknown tool '$tool', skipping"
    return
  fi

  [ -f "$src" ] || return

  local frontmatter body tmp
  frontmatter="$(awk 'NR==1 && /^---/ {p=1} p{print} p && NR>1 && /^---/{exit}' "$src")"
  body="$(strip_yaml_frontmatter "$src")"

  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$frontmatter"
    printf '%s\n\n' "$HEADER"
    printf '<!-- TOOL_IDENTITY=%s -->\n\n' "$tool"
    printf '%s\n' "$body" | sed "s/__TOOL_IDENTITY__/$tool/g"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

generate_orchestrate_skill() {
  local tool="$1"
  local src="$SCRIPT_DIR/skills/orchestrate/SKILL.md"
  local dst

  if [ "$tool" = "claude" ]; then
    dst="$AGENT_ROOT/.claude/skills/orchestrate/SKILL.md"
  elif [ "$tool" = "cursor" ]; then
    dst="$AGENT_ROOT/.cursor/skills/orchestrate/SKILL.md"
  else
    echo "  warning: generate_orchestrate_skill() — unknown tool '$tool', skipping"
    return
  fi

  [ -f "$src" ] || return

  local frontmatter body tmp
  frontmatter="$(awk 'NR==1 && /^---/ {p=1} p{print} p && NR>1 && /^---/{exit}' "$src")"
  body="$(strip_yaml_frontmatter "$src")"

  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$frontmatter"
    printf '%s\n\n' "$HEADER"
    printf '<!-- TOOL_IDENTITY=%s -->\n\n' "$tool"
    printf '%s\n' "$body" | sed "s/__TOOL_IDENTITY__/$tool/g"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

# ---------------------------------------------------------------------------
# Link generated files from AGENT_ROOT to REPO_ROOT (when they differ)
# ---------------------------------------------------------------------------
link_to_repo_root() {
  if [ "$AGENT_ROOT" = "$REPO_ROOT" ]; then
    return
  fi

  echo ""
  echo "Agent root ≠ repo root — linking generated files for tool discovery..."
  echo "  Agent root: $AGENT_ROOT"
  echo "  Repo root:  $REPO_ROOT"

  local linked=0
  local skipped=0

  for dir in ".claude" ".cursor"; do
    [ -d "$AGENT_ROOT/$dir" ] || continue

    # Create symlinks for each generated file at AGENT_ROOT
    while IFS= read -r src; do
      rel="${src#$AGENT_ROOT/}"
      dst="$REPO_ROOT/$rel"

      # Already a correct symlink — skip
      if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
        skipped=$((skipped + 1))
        continue
      fi

      # Regular file with identical content — skip (no link needed)
      if [ -f "$dst" ] && ! [ -L "$dst" ]; then
        if diff -q "$src" "$dst" >/dev/null 2>&1; then
          skipped=$((skipped + 1))
          continue
        fi
        # Different content — use strategy to decide
        case "$STRATEGY" in
          force|clean)
            rm -f "$dst"
            ;;
          keep)
            echo "  [S] $rel (kept existing at repo root)"
            skipped=$((skipped + 1))
            continue
            ;;
          "")
            CONFLICT_COUNT=$((CONFLICT_COUNT + 1))
            CONFLICT_FILES+=("$rel (repo root has different content)")
            echo "  [M] $rel (differs at repo root — not linking)"
            continue
            ;;
        esac
      fi

      # Remove stale symlink if present
      [ -L "$dst" ] && rm -f "$dst"

      mkdir -p "$(dirname "$dst")"
      ln -s "$src" "$dst"
      echo "  [L] $rel"
      linked=$((linked + 1))
    done < <(find "$AGENT_ROOT/$dir" -type f 2>/dev/null)

    # Clean dangling symlinks at REPO_ROOT that point into AGENT_ROOT
    if [ -d "$REPO_ROOT/$dir" ]; then
      while IFS= read -r dst; do
        [ -L "$dst" ] || continue
        target="$(readlink "$dst")"
        case "$target" in
          "$AGENT_ROOT/"*)
            if [ ! -e "$dst" ]; then
              rm -f "$dst"
              echo "  [D] ${dst#$REPO_ROOT/} (dangling link removed)"
            fi
            ;;
        esac
      done < <(find "$REPO_ROOT/$dir" -type l 2>/dev/null)
    fi
  done

  echo "  $linked linked, $skipped unchanged"
}

# ---------------------------------------------------------------------------
# Clean managed files (for --clean strategy)
# ---------------------------------------------------------------------------
clean_managed_files() {
  local tool="$1"
  local dir

  if [ "$tool" = "claude" ]; then
    dir="$AGENT_ROOT/.claude"
  elif [ "$tool" = "cursor" ]; then
    dir="$AGENT_ROOT/.cursor"
  else
    return
  fi

  [ -d "$dir" ] || return

  echo "  Cleaning setup-managed files in ${dir#$AGENT_ROOT/}..."
  grep -rl "AUTO-GENERATED by .agent/setup.sh" "$dir" 2>/dev/null | while read -r f; do
    rm -f "$f"
    echo "  [D] ${f#$AGENT_ROOT/}"
  done

  find "$dir" -type d -empty -delete 2>/dev/null || true

  # Also clean symlinks at REPO_ROOT that point into AGENT_ROOT (when they differ)
  if [ "$AGENT_ROOT" != "$REPO_ROOT" ]; then
    local repo_dir
    if [ "$tool" = "claude" ]; then
      repo_dir="$REPO_ROOT/.claude"
    else
      repo_dir="$REPO_ROOT/.cursor"
    fi
    if [ -d "$repo_dir" ]; then
      echo "  Cleaning symlinks in ${repo_dir#$REPO_ROOT/} (repo root)..."
      while IFS= read -r f; do
        [ -L "$f" ] || continue
        target="$(readlink "$f")"
        case "$target" in
          "$AGENT_ROOT/"*)
            rm -f "$f"
            echo "  [D] ${f#$REPO_ROOT/} (symlink)"
            ;;
        esac
      done < <(find "$repo_dir" -type l 2>/dev/null)
      find "$repo_dir" -type d -empty -delete 2>/dev/null || true
    fi
  fi
}

# ---------------------------------------------------------------------------
# Setup: Claude Code
# ---------------------------------------------------------------------------
setup_claude() {
  echo ""
  echo "Setting up Claude Code (.claude/)..."

  if [ "$STRATEGY" = "clean" ]; then
    clean_managed_files "claude"
  fi

  # Conduct
  copy_with_header "$SCRIPT_DIR/conduct.md" "$AGENT_ROOT/.claude/agent-conduct.md"

  # Knowledge
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "$AGENT_ROOT/.claude/knowledge/$(basename "$f")"
  done

  # Skills (directory-based: each skill is a dir with SKILL.md + optional supporting files)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    if [ "$skill_name" = "handoff" ] || [ "$skill_name" = "orchestrate" ]; then
      continue
    fi
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$AGENT_ROOT/.claude/skills/$skill_name/SKILL.md"
    fi
    while IFS= read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$AGENT_ROOT/.claude/skills/$skill_name/$rel"
    done < <(find "$skill_dir" -type f ! -name "SKILL.md")
  done

  # Tool-specific skill generation (handoff + orchestrate with TOOL_IDENTITY)
  generate_handoff_skill "claude"
  generate_orchestrate_skill "claude"

  # Agents
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    copy_plain "$f" "$AGENT_ROOT/.claude/agents/$(basename "$f")"
  done

  # Settings
  if [ -f "$SCRIPT_DIR/settings.json" ]; then
    copy_plain "$SCRIPT_DIR/settings.json" "$AGENT_ROOT/.claude/settings.json"
  fi

  echo ""
  echo "  MCP servers are defined in .agent/mcp.json."
  echo "  To configure Claude Code, add them to ~/.claude/settings.json under 'mcpServers'."
  echo "  See .agent/mcp.json for the server definitions."
  echo ""
  echo "Claude Code setup complete."
}

# ---------------------------------------------------------------------------
# Setup: Cursor
# ---------------------------------------------------------------------------
setup_cursor() {
  echo ""
  echo "Setting up Cursor (.cursor/)..."

  if [ "$STRATEGY" = "clean" ]; then
    clean_managed_files "cursor"
  fi

  # Conduct → always-applied .mdc rule
  wrap_mdc_rule \
    "$SCRIPT_DIR/conduct.md" \
    "Agent Code of Conduct — scope, quality gates, retry policy, Asana updates, code style, CI validation, and prohibited actions" \
    "true" \
    "$AGENT_ROOT/.cursor/rules/agent-conduct.mdc"

  # Knowledge → requestable .mdc rules
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    desc="$(head -1 "$f" | sed 's/^# //')"
    wrap_mdc_rule "$f" "$desc" "false" "$AGENT_ROOT/.cursor/rules/knowledge/$name.mdc"
  done

  # Agents → requestable .mdc rules (stripped of Claude-specific frontmatter)
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    generate_cursor_agent_rule "$f" "$AGENT_ROOT/.cursor/rules/agents/$name.mdc"
  done

  # Skills (directory-based: copy all skills to Cursor)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    if [ "$skill_name" = "handoff" ] || [ "$skill_name" = "orchestrate" ]; then
      continue
    fi
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$AGENT_ROOT/.cursor/skills/$skill_name/SKILL.md"
    fi
    while IFS= read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$AGENT_ROOT/.cursor/skills/$skill_name/$rel"
    done < <(find "$skill_dir" -type f ! -name "SKILL.md")
  done

  # Tool-specific skill generation (handoff + orchestrate with TOOL_IDENTITY)
  generate_handoff_skill "cursor"
  generate_orchestrate_skill "cursor"

  # MCP: generate .cursor/mcp.json from .agent/mcp.json
  local mcp_tmp
  mcp_tmp="$(mktemp)"
  node -e "
    const src = require('$SCRIPT_DIR/mcp.json');
    const out = { mcpServers: src.servers };
    process.stdout.write(JSON.stringify(out, null, 2) + '\n');
  " > "$mcp_tmp"
  write_file "$mcp_tmp" "$AGENT_ROOT/.cursor/mcp.json"
  rm -f "$mcp_tmp"

  echo ""
  echo "Cursor setup complete."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
target=""

for arg in "$@"; do
  case "$arg" in
    --force) STRATEGY="force" ;;
    --keep)  STRATEGY="keep" ;;
    --clean) STRATEGY="clean" ;;
    claude|cursor|all) target="$arg" ;;
    *)
      echo "Unknown argument: $arg"
      echo "Usage: $SCRIPT_REL/setup.sh [claude|cursor|all] [--force|--keep|--clean]"
      exit 1
      ;;
  esac
done

target="${target:-all}"

echo "=== Agent Config Setup ==="
echo "Source: $SCRIPT_REL/"
echo "Target: $target (→ $AGENT_ROOT)"
if [ -n "$STRATEGY" ]; then
  echo "Strategy: --$STRATEGY"
fi

if [ -d "$HANDOFF_DIR" ]; then
  rm -f "$HANDOFF_DIR"/*
  echo "  cleaned: ${HANDOFF_DIR#$AGENT_ROOT/} (removed stale handoff files)"
fi
mkdir -p "$HANDOFF_DIR"
echo "  created: ${HANDOFF_DIR#$AGENT_ROOT/}"

case "$target" in
  claude)
    setup_claude
    ;;
  cursor)
    setup_cursor
    ;;
  all)
    setup_claude
    setup_cursor
    ;;
  *)
    echo "Usage: $SCRIPT_REL/setup.sh [claude|cursor|all] [--force|--keep|--clean]"
    exit 1
    ;;
esac

# Link generated files to repo root (only when agent root differs)
link_to_repo_root

# Conflict report (default mode only)
if [ "$STRATEGY" = "" ] && [ "$CONFLICT_COUNT" -gt 0 ]; then
  echo ""
  echo "========================================="
  echo "Conflicts detected — $CONFLICT_COUNT file(s) differ from source:"
  echo ""
  for f in "${CONFLICT_FILES[@]}"; do
    echo "  [M] $f"
  done
  echo ""
  echo "Run again with a strategy:"
  echo "  bash $SCRIPT_REL/setup.sh $target --force   # overwrite all differing files"
  echo "  bash $SCRIPT_REL/setup.sh $target --keep    # keep existing, only add new files"
  echo "  bash $SCRIPT_REL/setup.sh $target --clean   # delete all managed files, regenerate"
  echo "========================================="
  exit 3
fi

echo ""
echo "Done. Generated files are marked AUTO-GENERATED — edit sources in .agent/ instead."
