#!/usr/bin/env bash
#
# .agent/setup.sh — Configure agent tooling for Claude Code and/or Cursor
#
# Usage: .agent/setup.sh [claude|cursor|all] [--force|--keep|--clean]
#
# Copies shared config from .agent/ into tool-specific directories at the git root.
# Checks for conflicts by default; use --force/--keep/--clean to resolve.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)" || {
  echo "ERROR: Not inside a git repository. setup.sh must be run from within a git repo."
  exit 1
}
SCRIPT_REL="${SCRIPT_DIR#$REPO_ROOT/}"

HEADER="<!-- AUTO-GENERATED by .agent/setup.sh — do not edit directly. Edit the source in .agent/ instead. -->"

# ---------------------------------------------------------------------------
# Strategy and conflict tracking
# ---------------------------------------------------------------------------
STRATEGY=""
CONFLICT_COUNT=0
declare -a CONFLICT_FILES=()

# ---------------------------------------------------------------------------
# Core write function — routes all file writes through conflict detection
# ---------------------------------------------------------------------------
write_file() {
  local tmp="$1"
  local dst="$2"
  local rel="${dst#$REPO_ROOT/}"

  mkdir -p "$(dirname "$dst")"

  if [ ! -f "$dst" ]; then
    cp "$tmp" "$dst"
    echo "  [N] $rel"
    return 0
  fi

  if diff -q "$tmp" "$dst" >/dev/null 2>&1; then
    echo "  [=] $rel (unchanged)"
    return 0
  fi

  case "$STRATEGY" in
    force|clean)
      cp "$tmp" "$dst"
      echo "  [U] $rel (updated)"
      ;;
    keep)
      echo "  [S] $rel (kept existing)"
      ;;
    "")
      CONFLICT_COUNT=$((CONFLICT_COUNT + 1))
      CONFLICT_FILES+=("$rel")
      echo "  [M] $rel (differs from source)"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
copy_with_header() {
  local src="$1"
  local dst="$2"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

copy_plain() {
  local src="$1"
  local dst="$2"
  local tmp
  tmp="$(mktemp)"
  cp "$src" "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

strip_yaml_frontmatter() {
  awk '
    BEGIN { in_front=0; found=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { in_front=0; found=1; next }
    in_front { next }
    found && NR>1 && /^\s*$/ && !printed { next }
    { printed=1; print }
  ' "$1"
}

wrap_with_frontmatter() {
  local src="$1"
  local name="$2"
  local description="$3"
  local dst="$4"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$description"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

wrap_mdc_rule() {
  local src="$1"
  local description="$2"
  local always_apply="$3"
  local dst="$4"
  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: %s\n---\n\n' "$description" "$always_apply"
    cat "$src"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

extract_frontmatter_field() {
  local file="$1"
  local field="$2"
  awk -v f="$field" '
    BEGIN { in_front=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { exit }
    in_front && $0 ~ "^"f":" {
      sub("^"f":[ ]*", "")
      gsub(/^"/, ""); gsub(/"$/, "")
      print
      exit
    }
  ' "$file"
}

generate_cursor_agent_rule() {
  local src="$1"
  local dst="$2"
  local agent_name
  agent_name="$(extract_frontmatter_field "$src" "name")"
  local description="Agent prompt: ${agent_name} — use as context when launching Task sub-agents"
  local body
  body="$(strip_yaml_frontmatter "$src")"

  local tmp
  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: false\n---\n\n' "$description"
    printf '%s\n' "$body" \
      | sed 's|`\.claude/agent-conduct\.md`|the agent conduct rules (`.cursor/rules/agent-conduct.mdc`)|g'
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

generate_handoff_skill() {
  local tool="$1"
  local src="$SCRIPT_DIR/skills/handoff/SKILL.md"
  local dst

  if [ "$tool" = "claude" ]; then
    dst="$REPO_ROOT/.claude/skills/handoff/SKILL.md"
  elif [ "$tool" = "cursor" ]; then
    dst="$REPO_ROOT/.cursor/skills/handoff/SKILL.md"
  else
    echo "  warning: generate_handoff_skill() — unknown tool '$tool', skipping"
    return
  fi

  [ -f "$src" ] || return

  local frontmatter body tmp
  frontmatter="$(awk 'NR==1 && /^---/ {p=1} p{print} p && NR>1 && /^---/{exit}' "$src")"
  body="$(strip_yaml_frontmatter "$src")"

  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$frontmatter"
    printf '%s\n\n' "$HEADER"
    printf '<!-- TOOL_IDENTITY=%s -->\n\n' "$tool"
    printf '%s\n' "$body" | sed "s/__TOOL_IDENTITY__/$tool/g"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

generate_orchestrate_skill() {
  local tool="$1"
  local src="$SCRIPT_DIR/skills/orchestrate/SKILL.md"
  local dst

  if [ "$tool" = "claude" ]; then
    dst="$REPO_ROOT/.claude/skills/orchestrate/SKILL.md"
  elif [ "$tool" = "cursor" ]; then
    dst="$REPO_ROOT/.cursor/skills/orchestrate/SKILL.md"
  else
    echo "  warning: generate_orchestrate_skill() — unknown tool '$tool', skipping"
    return
  fi

  [ -f "$src" ] || return

  local frontmatter body tmp
  frontmatter="$(awk 'NR==1 && /^---/ {p=1} p{print} p && NR>1 && /^---/{exit}' "$src")"
  body="$(strip_yaml_frontmatter "$src")"

  tmp="$(mktemp)"
  {
    printf '%s\n\n' "$frontmatter"
    printf '%s\n\n' "$HEADER"
    printf '<!-- TOOL_IDENTITY=%s -->\n\n' "$tool"
    printf '%s\n' "$body" | sed "s/__TOOL_IDENTITY__/$tool/g"
  } > "$tmp"
  write_file "$tmp" "$dst"
  rm -f "$tmp"
}

# ---------------------------------------------------------------------------
# Clean managed files (for --clean strategy)
# ---------------------------------------------------------------------------
clean_managed_files() {
  local tool="$1"
  local dir

  if [ "$tool" = "claude" ]; then
    dir="$REPO_ROOT/.claude"
  elif [ "$tool" = "cursor" ]; then
    dir="$REPO_ROOT/.cursor"
  else
    return
  fi

  [ -d "$dir" ] || return

  echo "  Cleaning setup-managed files in ${dir#$REPO_ROOT/}..."
  grep -rl "AUTO-GENERATED by .agent/setup.sh" "$dir" 2>/dev/null | while read -r f; do
    rm -f "$f"
    echo "  [D] ${f#$REPO_ROOT/}"
  done

  find "$dir" -type d -empty -delete 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Setup: Claude Code
# ---------------------------------------------------------------------------
setup_claude() {
  echo ""
  echo "Setting up Claude Code (.claude/)..."

  if [ "$STRATEGY" = "clean" ]; then
    clean_managed_files "claude"
  fi

  # Conduct
  copy_with_header "$SCRIPT_DIR/conduct.md" "$REPO_ROOT/.claude/agent-conduct.md"

  # Knowledge
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "$REPO_ROOT/.claude/knowledge/$(basename "$f")"
  done

  # Skills (directory-based: each skill is a dir with SKILL.md + optional supporting files)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    if [ "$skill_name" = "handoff" ] || [ "$skill_name" = "orchestrate" ]; then
      continue
    fi
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$REPO_ROOT/.claude/skills/$skill_name/SKILL.md"
    fi
    while IFS= read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$REPO_ROOT/.claude/skills/$skill_name/$rel"
    done < <(find "$skill_dir" -type f ! -name "SKILL.md")
  done

  # Tool-specific skill generation (handoff + orchestrate with TOOL_IDENTITY)
  generate_handoff_skill "claude"
  generate_orchestrate_skill "claude"

  # Agents
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    copy_plain "$f" "$REPO_ROOT/.claude/agents/$(basename "$f")"
  done

  # Settings
  if [ -f "$SCRIPT_DIR/settings.json" ]; then
    copy_plain "$SCRIPT_DIR/settings.json" "$REPO_ROOT/.claude/settings.json"
  fi

  echo ""
  echo "  MCP servers are defined in .agent/mcp.json."
  echo "  To configure Claude Code, add them to ~/.claude/settings.json under 'mcpServers'."
  echo "  See .agent/mcp.json for the server definitions."
  echo ""
  echo "Claude Code setup complete."
}

# ---------------------------------------------------------------------------
# Setup: Cursor
# ---------------------------------------------------------------------------
setup_cursor() {
  echo ""
  echo "Setting up Cursor (.cursor/)..."

  if [ "$STRATEGY" = "clean" ]; then
    clean_managed_files "cursor"
  fi

  # Conduct → always-applied .mdc rule
  wrap_mdc_rule \
    "$SCRIPT_DIR/conduct.md" \
    "Agent Code of Conduct — scope, quality gates, retry policy, Asana updates, code style, CI validation, and prohibited actions" \
    "true" \
    "$REPO_ROOT/.cursor/rules/agent-conduct.mdc"

  # Knowledge → requestable .mdc rules
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    desc="$(head -1 "$f" | sed 's/^# //')"
    wrap_mdc_rule "$f" "$desc" "false" "$REPO_ROOT/.cursor/rules/knowledge/$name.mdc"
  done

  # Agents → requestable .mdc rules (stripped of Claude-specific frontmatter)
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    generate_cursor_agent_rule "$f" "$REPO_ROOT/.cursor/rules/agents/$name.mdc"
  done

  # Skills (directory-based: copy all skills to Cursor)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    if [ "$skill_name" = "handoff" ] || [ "$skill_name" = "orchestrate" ]; then
      continue
    fi
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$REPO_ROOT/.cursor/skills/$skill_name/SKILL.md"
    fi
    while IFS= read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$REPO_ROOT/.cursor/skills/$skill_name/$rel"
    done < <(find "$skill_dir" -type f ! -name "SKILL.md")
  done

  # Tool-specific skill generation (handoff + orchestrate with TOOL_IDENTITY)
  generate_handoff_skill "cursor"
  generate_orchestrate_skill "cursor"

  # MCP: generate .cursor/mcp.json from .agent/mcp.json
  local mcp_tmp
  mcp_tmp="$(mktemp)"
  node -e "
    const src = require('$SCRIPT_DIR/mcp.json');
    const out = { mcpServers: src.servers };
    process.stdout.write(JSON.stringify(out, null, 2) + '\n');
  " > "$mcp_tmp"
  write_file "$mcp_tmp" "$REPO_ROOT/.cursor/mcp.json"
  rm -f "$mcp_tmp"

  echo ""
  echo "Cursor setup complete."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
target=""

for arg in "$@"; do
  case "$arg" in
    --force) STRATEGY="force" ;;
    --keep)  STRATEGY="keep" ;;
    --clean) STRATEGY="clean" ;;
    claude|cursor|all) target="$arg" ;;
    *)
      echo "Unknown argument: $arg"
      echo "Usage: $SCRIPT_REL/setup.sh [claude|cursor|all] [--force|--keep|--clean]"
      exit 1
      ;;
  esac
done

target="${target:-all}"

echo "=== Agent Config Setup ==="
echo "Source: $SCRIPT_REL/"
echo "Target: $target (→ repo root)"
if [ -n "$STRATEGY" ]; then
  echo "Strategy: --$STRATEGY"
fi

# Create shared handoff directory
if [ -d "$REPO_ROOT/.agent-handoff" ]; then
  rm -f "$REPO_ROOT/.agent-handoff"/*
  echo "  cleaned: .agent-handoff/ (removed stale handoff files)"
fi
mkdir -p "$REPO_ROOT/.agent-handoff"
echo "  created: .agent-handoff/"

case "$target" in
  claude)
    setup_claude
    ;;
  cursor)
    setup_cursor
    ;;
  all)
    setup_claude
    setup_cursor
    ;;
  *)
    echo "Usage: $SCRIPT_REL/setup.sh [claude|cursor|all] [--force|--keep|--clean]"
    exit 1
    ;;
esac

# Conflict report (default mode only)
if [ "$STRATEGY" = "" ] && [ "$CONFLICT_COUNT" -gt 0 ]; then
  echo ""
  echo "========================================="
  echo "Conflicts detected — $CONFLICT_COUNT file(s) differ from source:"
  echo ""
  for f in "${CONFLICT_FILES[@]}"; do
    echo "  [M] $f"
  done
  echo ""
  echo "Run again with a strategy:"
  echo "  bash $SCRIPT_REL/setup.sh $target --force   # overwrite all differing files"
  echo "  bash $SCRIPT_REL/setup.sh $target --keep    # keep existing, only add new files"
  echo "  bash $SCRIPT_REL/setup.sh $target --clean   # delete all managed files, regenerate"
  echo "========================================="
  exit 3
fi

echo ""
echo "Done. Generated files are marked AUTO-GENERATED — edit sources in .agent/ instead."
