#!/usr/bin/env bun
/**
 * Writes the block of `_redirects` rules that keeps every pre-move URL
 * resolving after the collections reorganization.
 *
 * The rules are generated from the move mapping rather than written by hand:
 * the reorganization renamed all 69 pages at once, and a single omission
 * silently 404s a URL that search engines and external links already point
 * at. Generating them from the same mapping that performed the move makes a
 * page-without-a-redirect impossible.
 *
 * Two rules per moved page, because both were public entry points:
 *   - the page URL          `/quickstart/`     → `/sdk/quickstart/`
 *   - its Markdown twin     `/quickstart.md`   → `/sdk/quickstart.md`
 *
 * The block is spliced between two markers, so re-running is idempotent and
 * the hand-written rules around it are never touched. It lands above the
 * terminal catch-all, which is first-match-wins and would otherwise swallow
 * every one of these.
 *
 * Usage:
 *   bun run scripts/generate-redirects.ts           # rewrite the block
 *   bun run scripts/generate-redirects.ts --check   # fail if it is stale
 */

import * as fs from "fs/promises";
import * as path from "path";
import { fileURLToPath } from "node:url";
import { loadMoveMap, type Move } from "./collections-move-map.js";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DOCS_WEBSITE_DIR = path.resolve(SCRIPT_DIR, "..");
const REDIRECTS_PATH = path.join(DOCS_WEBSITE_DIR, "public", "_redirects");

const BEGIN_MARKER =
  "# >>> BEGIN generated by scripts/generate-redirects.ts — do not edit by hand";
const END_MARKER = "# <<< END generated";

/** `/quickstart` → `/quickstart/`, `/` stays `/`. */
function asDirectory(url: string): string {
  return url === "/" ? "/" : `${url}/`;
}

/**
 * The per-page Markdown file agents fetch by appending `.md` to a page URL.
 * The home page's twin is `/index.md`, mirroring how it is exported.
 */
function asMarkdown(url: string): string {
  return url === "/" ? "/index.md" : `${url}.md`;
}

export function buildRedirectLines(moves: Move[]): string[] {
  const byUrl = [...moves]
    // A page whose URL the move left alone needs no rule, and a rule whose
    // source is the page itself would be a loop the CDN answers before the
    // page does.
    .filter((move) => move.fromUrl !== move.toUrl)
    .sort((a, b) => a.fromUrl.localeCompare(b.fromUrl));
  const pairs: Array<[string, string]> = [];
  for (const move of byUrl) {
    pairs.push([asDirectory(move.fromUrl), asDirectory(move.toUrl)]);
  }
  for (const move of byUrl) {
    pairs.push([asMarkdown(move.fromUrl), asMarkdown(move.toUrl)]);
  }

  const fromWidth = Math.max(...pairs.map(([from]) => from.length));
  const toWidth = Math.max(...pairs.map(([, to]) => to.length));
  return pairs.map(
    ([from, to]) => `${from.padEnd(fromWidth + 3)}${to.padEnd(toWidth + 3)}301`,
  );
}

function buildBlock(moves: Move[]): string {
  const lines = buildRedirectLines(moves);
  const pages = lines.length / 2;
  return [
    BEGIN_MARKER,
    "#",
    `# One 301 per moved page (${pages}), then one per Markdown twin (${pages}).`,
    "# Regenerate with: bun run scripts/generate-redirects.ts",
    "",
    ...lines,
    "",
    END_MARKER,
  ].join("\n");
}

function splice(current: string, block: string): string {
  const begin = current.indexOf(BEGIN_MARKER);
  const end = current.indexOf(END_MARKER);

  if (begin === -1 || end === -1) {
    throw new Error(
      `Markers not found in ${REDIRECTS_PATH}. Add them above the catch-all rule:\n${BEGIN_MARKER}\n${END_MARKER}`,
    );
  }
  if (end < begin) {
    throw new Error("End marker precedes begin marker in _redirects");
  }

  return (
    current.slice(0, begin) + block + current.slice(end + END_MARKER.length)
  );
}

async function main() {
  const check = process.argv.includes("--check");
  const current = await fs.readFile(REDIRECTS_PATH, "utf-8");
  const moves = await loadMoveMap();
  const updated = splice(current, buildBlock(moves));

  if (check) {
    if (updated !== current) {
      throw new Error(
        "public/_redirects is stale — run `bun run scripts/generate-redirects.ts`",
      );
    }
    console.log(
      `_redirects is up to date (${buildRedirectLines(moves).length} rules)`,
    );
    return;
  }

  await fs.writeFile(REDIRECTS_PATH, updated, "utf-8");
  const pages = buildRedirectLines(moves).length / 2;
  console.log(
    `Wrote ${pages * 2} rules (${pages} pages + ${pages} Markdown twins) to public/_redirects`,
  );
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
