import RPC from "bare-rpc";
import spawn, {
  type ChildProcess as BareChildProcess,
} from "bare-runtime/spawn";
import type { Duplex, DuplexEvents } from "bare-stream";
import { randomBytes } from "node:crypto";
import { existsSync, unlinkSync } from "node:fs";
import { createServer } from "node:net";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.node";
import { getClientLogger } from "@/logging";
import {
  RPCInitTimeoutError,
  WorkerCrashedError,
  WorkerShutdownError,
} from "@/utils/errors-client";
import type { RuntimeContext } from "@/schemas";

const RPC_INIT_TIMEOUT_MS = 30_000;

const logger = getClientLogger();

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;
let bareWorkerProc: BareChildProcess | null = null;
let ipcServer: ReturnType<typeof createServer> | null = null;
let currentSocketPath: string | null = null;
let closePromise: Promise<void> | null = null;
// Aborted when the worker dies (crash) or close() runs (planned). Used
// to unblock in-flight `req.reply()` callers — bare-rpc's `_onerror`
// does not iterate `_outgoingRequests`, so without this signal they
// would hang on the dead socket.
let workerLifeController: AbortController | null = null;

/**
 * Find project root by looking for package.json (sync version)
 * Safe to call at module load time
 */
function findProjectRootSync(): string | undefined {
  let dir = process.cwd();
  const root = path.parse(dir).root;

  while (dir !== root) {
    if (fs.existsSync(path.join(dir, "package.json"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }

  return undefined;
}

function getResourcesPathSync(): string | undefined {
  const { resourcesPath } = process as { resourcesPath?: string };
  return typeof resourcesPath === "string" ? resourcesPath : undefined;
}

function resolvePackagedWorkerPath(): string | undefined {
  const resourcesPath = getResourcesPathSync();
  if (!resourcesPath) return undefined;

  const candidates = [
    path.join(resourcesPath, "app.asar.unpacked", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "app", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "qvac", "worker.entry.mjs"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }

  return undefined;
}

/**
 * Resolve the SDK's default worker entry via bundler-visible asset references.
 *
 * `path.resolve(__dirname, ...)` is invisible to static analysis, so packaged
 * consumers ship without worker.js. We use `import.meta.asset(<literal>)` on
 * Bare (detected by bare-module-lexer) and fall back to
 * `new URL(<literal>, import.meta.url)` elsewhere. Specs must be string
 * literals at the call site.
 */
function getDefaultWorkerPath(): string {
  type ImportMetaAsset = { asset?: (spec: string) => string };
  const hasAsset =
    typeof (import.meta as ImportMetaAsset).asset === "function";

  const packagedUrl = hasAsset
    ? new URL(
        (import.meta as ImportMetaAsset).asset!("../../server/worker.js"),
      )
    : new URL("../../server/worker.js", import.meta.url);
  const packaged = fileURLToPath(packagedUrl);
  if (fs.existsSync(packaged)) return packaged;

  // Dev/source layout fallback
  const devUrl = hasAsset
    ? new URL(
        (import.meta as ImportMetaAsset).asset!("../../dist/server/worker.js"),
      )
    : new URL("../../dist/server/worker.js", import.meta.url);
  return fileURLToPath(devUrl);
}

/**
 * Resolve worker path with priority:
 * 1. QVAC_WORKER_PATH environment variable
 * 2. Packaged Electron app worker entry
 * 3. qvac/worker.entry.mjs in project root (generated by npx qvac bundle sdk)
 * 4. Default SDK worker
 */
function resolveWorkerPath(): string {
  const envWorkerPath = process.env["QVAC_WORKER_PATH"] as string | undefined;
  if (envWorkerPath) {
    const normalized = path.resolve(envWorkerPath);
    if (fs.existsSync(normalized)) {
      logger.info(`🔧 Using worker entry from QVAC_WORKER_PATH: ${normalized}`);
      return normalized;
    }
    logger.warn(
      `⚠️ QVAC_WORKER_PATH was set but file was not found: ${normalized}. Falling back.`,
    );
  }

  // Prefer packaged worker entry when running as a packaged Electron app.
  // This avoids accidental coupling to the project's cwd, and ensures the
  // bare worker reads JS modules from the filesystem (not app.asar).
  const packagedWorker = resolvePackagedWorkerPath();
  if (packagedWorker) {
    logger.info(`🔧 Using packaged worker entry: ${packagedWorker}`);
    return packagedWorker;
  }

  // Check for custom worker entry at project root
  // Note: We use worker.entry.mjs (unbundled ESM) for desktop because bare can
  // load ES modules directly. The packed bundle is for mobile only.
  const projectRoot = findProjectRootSync();
  if (projectRoot) {
    const customEntry = path.join(projectRoot, "qvac", "worker.entry.mjs");
    if (fs.existsSync(customEntry)) {
      logger.info(`🔧 Using custom worker entry: ${customEntry}`);
      return customEntry;
    }
  }

  // Fallback to default SDK worker
  const defaultPath = getDefaultWorkerPath();
  logger.debug(`🔧 Using default SDK worker: ${defaultPath}`);
  return defaultPath;
}

const WORKER_PATH = resolveWorkerPath();

function createSocketPath() {
  const timestamp = Date.now().toString(36);
  const randomSuffix = randomBytes(2).toString("hex");
  const socketName = `qvac-worker-${process.pid}-${timestamp}-${randomSuffix}`;
  return process.platform === "win32"
    ? `\\\\.\\pipe\\${socketName}`
    : path.join(os.tmpdir(), `${socketName}.sock`);
}

function bestEffortUnlinkSocket(socketPath: string | null) {
  // Windows named pipes are not filesystem paths, so unlink is Unix-only.
  if (!socketPath || process.platform === "win32") return;
  try {
    if (existsSync(socketPath)) {
      unlinkSync(socketPath);
    }
  } catch (error) {
    logger.debug("Failed to unlink IPC socket path", { socketPath, error });
  }
}

function snapshotAndResetState() {
  const workerToClose = bareWorkerProc;
  const serverToClose = ipcServer;
  const socketPathToClose = currentSocketPath;

  rpcInstance = null;
  rpcPromise = null;
  bareWorkerProc = null;
  ipcServer = null;
  currentSocketPath = null;
  workerLifeController = null;

  return { workerToClose, serverToClose, socketPathToClose };
}

export function getWorkerLifeSignal(): AbortSignal | null {
  return workerLifeController?.signal ?? null;
}

interface SpawnResources {
  controller: AbortController;
  server: ReturnType<typeof createServer>;
  socketPath: string;
}

// `spawn` carries this listener's own captured resources. Module-level
// state may belong to a newer ensureRPC() by the time we fire.
function handlePostHandshakeExit(
  code: number | null,
  exitSignal: NodeJS.Signals | null,
  spawn: SpawnResources,
): void {
  if (spawn.controller.signal.aborted) {
    // close() already handled teardown.
    logger.debug(
      `Bare worker exited after planned shutdown (code=${code}, signal=${exitSignal})`,
    );
    return;
  }

  logger.info(
    `🪦 Bare worker exited post-handshake (code=${code}, signal=${exitSignal})`,
  );

  // Only clear module state if we're still the active spawn.
  if (workerLifeController === spawn.controller) {
    rpcInstance = null;
    rpcPromise = null;
    bareWorkerProc = null;
    ipcServer = null;
    currentSocketPath = null;
    workerLifeController = null;
  }

  try {
    spawn.server.close();
  } catch (err) {
    logger.debug("Failed to close IPC server after worker crash", { err });
  }
  spawn.controller.abort(new WorkerCrashedError(code, exitSignal));
  bestEffortUnlinkSocket(spawn.socketPath);
}

function closeSyncForExit() {
  // Abort before kill so the exit handler sees planned intent.
  workerLifeController?.abort(new WorkerShutdownError());

  const { workerToClose, serverToClose, socketPathToClose } =
    snapshotAndResetState();

  if (workerToClose) {
    try {
      workerToClose.kill("SIGTERM");
    } catch (error) {
      logger.debug("Failed to kill bare worker during process exit", { error });
    }
  }

  if (serverToClose) {
    try {
      serverToClose.close();
    } catch (error) {
      logger.debug("Failed to close IPC server during process exit", { error });
    }
  }

  bestEffortUnlinkSocket(socketPathToClose);
}

async function ensureRPC(): Promise<RPC> {
  if (rpcInstance) return rpcInstance;
  if (rpcPromise) return rpcPromise;
  if (closePromise) {
    await closePromise;
  }

  const socketPath = createSocketPath();
  currentSocketPath = socketPath;

  // Allocated here so the init race and exit handler share one controller.
  const spawnController = new AbortController();
  workerLifeController = spawnController;

  rpcPromise = new Promise((resolve, reject) => {
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      rpcPromise = null;
      rpcInstance = null;
      bareWorkerProc = null;
      ipcServer = null;
      currentSocketPath = null;
      workerLifeController = null;
      reject(new RPCInitTimeoutError(RPC_INIT_TIMEOUT_MS));
    }, RPC_INIT_TIMEOUT_MS);

    ipcServer = createServer((socket) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      rpcInstance = new RPC(
        socket as unknown as Duplex<DuplexEvents>,
        () => {},
      );
      resolve(rpcInstance);
    });

    ipcServer.on("error", (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      rpcPromise = null;
      rpcInstance = null;
      bareWorkerProc = null;
      ipcServer = null;
      currentSocketPath = null;
      workerLifeController = null;
      reject(error);
    });

    ipcServer.listen(socketPath, () => {
      const spawnResources: SpawnResources = {
        controller: spawnController,
        server: ipcServer!,
        socketPath,
      };

      bareWorkerProc = spawn("bare", {
        args: [
          WORKER_PATH,
          JSON.stringify({
            QVAC_IPC_SOCKET_PATH: socketPath,
            // Snap's HOME can be revision-scoped; SNAP_USER_COMMON is stable.
            HOME_DIR: process.env["SNAP_USER_COMMON"]
              ? String(process.env["SNAP_USER_COMMON"])
              : os.homedir(),
          }),
        ],
        stdio: ["inherit", "inherit", "inherit"],
      });

      if (bareWorkerProc) {
        bareWorkerProc.on(
          "exit",
          (code: number | null, exitSignal: string | null) => {
            if (settled) {
              handlePostHandshakeExit(
                code,
                exitSignal as NodeJS.Signals | null,
                spawnResources,
              );
              return;
            }
            // Worker died before handshake — reject the init promise.
            settled = true;
            clearTimeout(timer);
            rpcPromise = null;
            rpcInstance = null;
            bareWorkerProc = null;
            ipcServer = null;
            currentSocketPath = null;
            workerLifeController = null;
            reject(
              new RPCInitTimeoutError(
                RPC_INIT_TIMEOUT_MS,
                new Error(
                  `Worker process exited with code ${code} before IPC connection was established`,
                ),
              ),
            );
          },
        );
      }
    });
  });

  const rpc = await rpcPromise;

  const runtimeContext: RuntimeContext = {
    runtime: "node",
    platform: process.platform as "darwin" | "linux" | "win32",
  };

  // init-hooks calls bare-rpc directly, bypassing rpc-client's race.
  await Promise.race([
    initializeConfig(rpc, resolveConfig, runtimeContext),
    rejectOnAbort(spawnController.signal),
  ]);

  return rpc;
}

function rejectOnAbort(signal: AbortSignal): Promise<never> {
  return new Promise((_, reject) => {
    const fail = () =>
      reject(
        signal.reason instanceof Error
          ? signal.reason
          : new WorkerCrashedError(null, null),
      );
    if (signal.aborted) {
      fail();
      return;
    }
    signal.addEventListener("abort", fail, { once: true });
  });
}

export async function getRPC() {
  return ensureRPC();
}

export async function createDuplexSession(payload: string, commandId: number) {
  const rpc = await ensureRPC();
  const req = rpc.request(commandId);
  const requestStream = req.createRequestStream();
  const responseStream = req.createResponseStream({ encoding: "utf-8" });
  requestStream.write(payload, "utf-8");

  // Destroy on worker death so consumers' for-await throws instead of hangs.
  const lifeSignal = workerLifeController?.signal;
  if (lifeSignal && !lifeSignal.aborted) {
    const onAbort = () => {
      const err =
        lifeSignal.reason instanceof Error
          ? lifeSignal.reason
          : new WorkerCrashedError(null, null);
      try {
        (requestStream as { destroy?: (err?: Error) => void }).destroy?.(err);
      } catch {}
      try {
        (responseStream as { destroy?: (err?: Error) => void }).destroy?.(err);
      } catch {}
    };
    lifeSignal.addEventListener("abort", onAbort, { once: true });
  }

  return { requestStream, responseStream };
}

export async function close() {
  if (closePromise) {
    await closePromise;
    return;
  }

  if (!rpcInstance && !rpcPromise && !bareWorkerProc && !ipcServer) return;

  logger.info("🧹 Closing RPC client");

  // Abort before kill: exit handler sees planned intent; any in-flight
  // caller (contract violators) rejects with WorkerShutdownError.
  workerLifeController?.abort(new WorkerShutdownError());

  const { workerToClose, serverToClose, socketPathToClose } =
    snapshotAndResetState();

  closePromise = (async () => {
    if (workerToClose) {
      logger.info("🐻🔫 Killing bare worker process");
      try {
        workerToClose.kill("SIGTERM");
      } catch (error) {
        logger.debug("Failed to kill bare worker process", { error });
      }
    }

    if (serverToClose) {
      logger.info("🔌 Closing IPC server");
      await new Promise<void>((resolve) => {
        try {
          serverToClose.close(() => resolve());
        } catch (error) {
          logger.debug("Failed to close IPC server", { error });
          resolve();
        }
      });
    }

    bestEffortUnlinkSocket(socketPathToClose);
  })();

  try {
    await closePromise;
  } finally {
    closePromise = null;
  }
}

function handleTerminationSignal(signal: NodeJS.Signals) {
  logger.info(`Received ${signal}, closing RPC resources...`);
  closeSyncForExit();
  process.kill(process.pid, signal);
}

process.once("SIGINT", () => handleTerminationSignal("SIGINT"));
process.once("SIGTERM", () => handleTerminationSignal("SIGTERM"));
process.once("SIGHUP", () => handleTerminationSignal("SIGHUP"));
process.once("exit", closeSyncForExit);
