packages:
  - "packages/classification-ggml"
  - "packages/fabric"
  - "packages/infer-base"
  - "packages/logging"

linkWorkspacePackages: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@qvac/fabric@0.3.1'

allowBuilds:
  nx: true
  unrs-resolver: true
