'use strict'
// QVAC-19178: VLM benchmark fixture — AUTO-GENERATED by scripts/build-vlm-fixture.cjs.
// Open-licensed samples (see vlm-fixture.NOTICE.md), longest side <= 1024px.
module.exports = {
  "tasks": [
    "textvqa",
    "vizwiz",
    "gqa",
    "docvqa",
    "ai2d"
  ],
  "samplesPerTask": 3,
  "items": [
    {
      "id": "textvqa_0",
      "task": "textvqa",
      "metric": "vqa",
      "prompt": "who was the photographer?\nAnswer the question using a single word or phrase.",
      "gold": [
        "philippe molitor",
        "philippe molitor",
        "philippe molitor",
        "philippe molitor",
        "clardajne",
        "phillipe molida",
        "l",
        "no",
        "phillipe meltow",
        "philippe molitar"
      ],
      "image": "vlmx-textvqa_0.jpg",
      "width": 1024,
      "height": 681,
      "license": "CC-BY-4.0"
    },
    {
      "id": "textvqa_1",
      "task": "textvqa",
      "metric": "vqa",
      "prompt": "what time is it?\nAnswer the question using a single word or phrase.",
      "gold": [
        "13:50",
        "13:57",
        "13:57",
        "13:57",
        "13:57",
        "mathematic",
        ";5713",
        "wifi",
        "13:57 ",
        "13:57"
      ],
      "image": "vlmx-textvqa_1.jpg",
      "width": 1024,
      "height": 576,
      "license": "CC-BY-4.0"
    },
    {
      "id": "textvqa_2",
      "task": "textvqa",
      "metric": "vqa",
      "prompt": "what is the date on the text?\nAnswer the question using a single word or phrase.",
      "gold": [
        "1855",
        "1855",
        "1855",
        "1855",
        "1855",
        "1855",
        "1855",
        "1805",
        "1855",
        "1855"
      ],
      "image": "vlmx-textvqa_2.jpg",
      "width": 1024,
      "height": 790,
      "license": "CC-BY-4.0"
    },
    {
      "id": "vizwiz_0",
      "task": "vizwiz",
      "metric": "vqa",
      "prompt": "Is there text or any identifying identification on this side of the card?\nAnswer the question using a single word or phrase.",
      "gold": [
        "no text identifying identification on side card",
        "yes",
        "unanswerable",
        "no",
        "no",
        "unanswerable",
        "unanswerable",
        "no",
        "no",
        "no"
      ],
      "image": "vlmx-vizwiz_0.jpg",
      "width": 360,
      "height": 480,
      "license": "CC-BY-4.0"
    },
    {
      "id": "vizwiz_1",
      "task": "vizwiz",
      "metric": "vqa",
      "prompt": "Can you tell me what the screen says? The screen capture security code please.\nAnswer the question using a single word or phrase.",
      "gold": [
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno",
        "nikeno"
      ],
      "image": "vlmx-vizwiz_1.jpg",
      "width": 320,
      "height": 568,
      "license": "CC-BY-4.0"
    },
    {
      "id": "vizwiz_2",
      "task": "vizwiz",
      "metric": "vqa",
      "prompt": "What's on the screen\nAnswer the question using a single word or phrase.",
      "gold": [
        "text",
        "website url",
        "please visit: wwwhpcom go techcenter",
        "unanswerable",
        "visit: wwwhpcom go techcenter",
        "please visit: wwwhpcom go techcenter",
        "website",
        "unanswerable",
        "web address",
        "full computer screen not shown on image"
      ],
      "image": "vlmx-vizwiz_2.jpg",
      "width": 768,
      "height": 1024,
      "license": "CC-BY-4.0"
    },
    {
      "id": "gqa_0",
      "task": "gqa",
      "metric": "vqa",
      "prompt": "Who is wearing the shirt?\nAnswer the question using a single word or phrase.",
      "gold": [
        "girl"
      ],
      "image": "vlmx-gqa_0.jpg",
      "width": 500,
      "height": 331,
      "license": "CC-BY-4.0"
    },
    {
      "id": "gqa_1",
      "task": "gqa",
      "metric": "vqa",
      "prompt": "Which color is the cake?\nAnswer the question using a single word or phrase.",
      "gold": [
        "white"
      ],
      "image": "vlmx-gqa_1.jpg",
      "width": 640,
      "height": 480,
      "license": "CC-BY-4.0"
    },
    {
      "id": "gqa_2",
      "task": "gqa",
      "metric": "vqa",
      "prompt": "Who is wearing a wristband?\nAnswer the question using a single word or phrase.",
      "gold": [
        "woman"
      ],
      "image": "vlmx-gqa_2.jpg",
      "width": 640,
      "height": 427,
      "license": "CC-BY-4.0"
    },
    {
      "id": "docvqa_0",
      "task": "docvqa",
      "metric": "anls",
      "prompt": "What is the rightmost word in first line?\nAnswer the question using a single word or phrase.",
      "gold": [
        "Active"
      ],
      "image": "vlmx-docvqa_0.jpg",
      "width": 584,
      "height": 325,
      "license": "Apache-2.0"
    },
    {
      "id": "docvqa_1",
      "task": "docvqa",
      "metric": "anls",
      "prompt": "What draft is attached to the letter?\nAnswer the question using a single word or phrase.",
      "gold": [
        "draft of minutes of yesterday's Committee Meeting, subject to approval of counsel",
        "minutes of yesterday's Committee Meeting",
        "draft of minutes of yesterday's committee meeting, subject to approval of counsel",
        "minutes of yesterday's committee meeting",
        "minutes of yesterday's committee meeting, subject to approval of counsel",
        "draft of minutes of yesterday's committee meeting"
      ],
      "image": "vlmx-docvqa_1.jpg",
      "width": 804,
      "height": 502,
      "license": "Apache-2.0"
    },
    {
      "id": "docvqa_2",
      "task": "docvqa",
      "metric": "anls",
      "prompt": "Which country's document is this based on the \"Printed\" details at the footer?\nAnswer the question using a single word or phrase.",
      "gold": [
        "U.S.A."
      ],
      "image": "vlmx-docvqa_2.jpg",
      "width": 904,
      "height": 725,
      "license": "Apache-2.0"
    },
    {
      "id": "ai2d_0",
      "task": "ai2d",
      "metric": "mc",
      "prompt": "What stage comes after egg?\nA. beetle\nB. caterpillar\nC. pupa\nD. mealworm\nAnswer with ONLY the letter (for example, A) of the correct option, and nothing else.",
      "gold": [
        "D"
      ],
      "image": "vlmx-ai2d_0.jpg",
      "width": 350,
      "height": 300,
      "license": "CC-BY-SA-4.0"
    },
    {
      "id": "ai2d_1",
      "task": "ai2d",
      "metric": "mc",
      "prompt": "What is energy\nA. sun\nB. C\nC. B\nD. A\nAnswer with ONLY the letter (for example, A) of the correct option, and nothing else.",
      "gold": [
        "A"
      ],
      "image": "vlmx-ai2d_1.jpg",
      "width": 574,
      "height": 246,
      "license": "CC-BY-SA-4.0"
    },
    {
      "id": "ai2d_2",
      "task": "ai2d",
      "metric": "mc",
      "prompt": "What does the bird feed on/\nA. zooplankton\nB. grass\nC. predator fish\nD. none of the above\nAnswer with ONLY the letter (for example, A) of the correct option, and nothing else.",
      "gold": [
        "C"
      ],
      "image": "vlmx-ai2d_2.jpg",
      "width": 720,
      "height": 259,
      "license": "CC-BY-SA-4.0"
    }
  ]
}
