#!/usr/bin/env bun
/**
 * Updates src/lib/versions.ts from content/docs/sdk/api/ version folders.
 * Production implementation per API-DOCS-AUTOMATION-COMPLETE-GUIDE Appendix E.
 *
 * Usage: bun run scripts/update-versions-list.ts [version]
 * Version arg is optional; if provided, ensures that version is included (e.g. after generating).
 */

import * as fs from "fs/promises";
import * as path from "path";

async function updateVersionsList(newVersion?: string) {
  console.log(`📋 Updating versions list...`);

  const versionsFile = path.join(process.cwd(), "src", "lib", "versions.ts");
  const apiDir = path.join(process.cwd(), "content", "docs", "sdk", "api");

  let entries;
  try {
    entries = await fs.readdir(apiDir, { withFileTypes: true });
  } catch (err) {
    throw new Error(
      `Failed to read API directory: ${apiDir}. Generate docs first.`
    );
  }

  const versions = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter(
      (name) =>
        name !== "latest" &&
        name !== ".latest-backup"
    )
    .filter((name) => /^v\d+\.\d+\.\d+$/.test(name))
    .sort((a, b) => {
      const aVer = a.replace("v", "").split(".").map(Number);
      const bVer = b.replace("v", "").split(".").map(Number);
      for (let i = 0; i < 3; i++) {
        if (aVer[i] !== bVer[i]) return bVer[i] - aVer[i];
      }
      return 0;
    });

  console.log(`✓ Found ${versions.length} versions:`, versions.join(", ") || "(none)");

  if (newVersion) {
    const normalized = newVersion.startsWith("v") ? newVersion : `v${newVersion}`;
    if (!versions.includes(normalized)) {
      throw new Error(
        `Version ${normalized} was not found in ${apiDir}. ` +
        `Did docs:generate-api run successfully for this version?`
      );
    }
    console.log(`✓ Confirmed ${normalized} is present`);
  }

  if (versions.length === 0) {
    throw new Error(
      "No valid version directories (vX.Y.Z) found. Run docs:generate-api first."
    );
  }

  const latestVersion = versions[0];
  const content = `// Auto-generated by scripts/update-versions-list.ts
// DO NOT EDIT MANUALLY - Changes will be overwritten

export interface Version {
  label: string;
  path: string;
  isLatest?: boolean;
}

export const VERSIONS: Version[] = [
  { label: 'Latest (v${latestVersion.replace("v", "")})', path: 'latest', isLatest: true },
${versions.map((v) => `  { label: '${v}', path: '${v}' },`).join("\n")}
];

export const LATEST_VERSION = '${latestVersion}';

/**
 * Extract version from URL pathname
 * @example getVersionFromPath('/docs/sdk/api/v0.6.1/loadModel') → 'v0.6.1'
 */
export function getVersionFromPath(pathname: string): string | null {
  const match = pathname.match(/\\/docs\\/sdk\\/api\\/(v[\\d.]+|latest)\\//);
  return match?.[1] ?? null;
}
`;

  await fs.writeFile(versionsFile, content, "utf-8");
  console.log(`✅ Updated ${versionsFile}`);
  console.log(`   Latest: ${latestVersion}`);
  console.log(`   Total versions: ${versions.length}`);
}

const newVersion = process.argv[2];
if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log("Usage: bun run scripts/update-versions-list.ts [version]");
  console.log("  version  Optional. After generating a new version, pass it to refresh the list.");
  process.exit(0);
}

updateVersionsList(newVersion).catch((error) => {
  console.error("❌ Error updating versions list:", error.message);
  if (error.stack) console.error(error.stack);
  process.exit(1);
});
