import { z } from 'zod'

const noulQuestionSchema = z.object({
  type: z.literal('noul'),
  instructions: z.unknown().describe('The question. A string, object, or array.'),
  criteria: z
    .record(z.string(), z.unknown())
    .optional()
    .describe('Optional descriptions for the `false` and `true` labels.')
})

const choiceQuestionSchema = z.object({
  type: z.literal('choice'),
  instructions: z.unknown().describe('The question. A string, object, or array.'),
  criteria: z
    .record(z.string(), z.unknown())
    .refine((criteria) => Object.keys(criteria).length > 0, {
      message: '"criteria" must be a non-empty object'
    })
    .describe('Option id to description. One option is valid. An empty object is not.')
})

const scoreQuestionSchema = z.object({
  type: z.literal('score'),
  instructions: z.unknown().describe('The question. A string, object, or array.'),
  criteria: z
    .array(z.unknown())
    .min(2)
    .max(10)
    .describe('Level descriptions, lowest first. Length 2 to 10.')
})

export const decisionQuestionSchema = z.discriminatedUnion('type', [
  noulQuestionSchema,
  choiceQuestionSchema,
  scoreQuestionSchema
])

export const decideParamsSchema = z.object({
  modelId: z.string().min(1).describe('The identifier of the loaded decision model'),
  state: z
    .unknown()
    .refine((state) => state !== null && state !== undefined, {
      message: '"state" must be provided'
    })
    .describe('Content to score. A string, object, or array. Null is rejected.'),
  questions: z
    .record(z.string(), decisionQuestionSchema)
    .refine((questions) => Object.keys(questions).length > 0, {
      message: '"questions" must be a non-empty object'
    })
    .describe('Question id to a noul, choice, or score question.'),
  images: z
    .array(z.string())
    .optional()
    .describe(
      'Optional image data URLs. Text-only decision models reject this. The field is the extension hook; this package does not decode images.'
    )
})

export const decideRequestSchema = decideParamsSchema.extend({
  type: z.literal('decide'),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Stable identifier for this in-flight decide, generated by the caller at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`.'
    )
})

const noulAnswerSchema = z.object({
  type: z.literal('noul'),
  noul: z.number().describe('Probability that the answer is true. No confidence field.')
})

const choiceAnswerSchema = z.object({
  type: z.literal('choice'),
  choice: z.string(),
  probabilities: z.record(z.string(), z.number()),
  confidence: z.number()
})

const scoreAnswerSchema = z.object({
  type: z.literal('score'),
  score: z.number().describe('Expected level index. It can fall between two levels.'),
  legend: z.record(z.string(), z.unknown()),
  probabilities: z.record(z.string(), z.number()),
  confidence: z.number()
})

export const decisionAnswerSchema = z.discriminatedUnion('type', [
  noulAnswerSchema,
  choiceAnswerSchema,
  scoreAnswerSchema
])

export const decideUsageSchema = z.object({
  input_tokens: z.number(),
  output_tokens: z.literal(0)
})

export const decideResponseSchema = z.object({
  type: z.literal('decide'),
  success: z.boolean(),
  answers: z.record(z.string(), decisionAnswerSchema),
  usage: decideUsageSchema,
  error: z.string().optional()
})

export const decideConfigBaseSchema = z.object({
  device: z
    .enum(['cpu', 'gpu'])
    .optional()
    .describe('Device to run on. Default is left to the addon.'),
  verbosity: z
    .number()
    .int()
    .min(0)
    .max(3)
    .optional()
    .describe('Native log verbosity: 0=ERROR, 1=WARN, 2=INFO, 3=DEBUG.')
})

export type DecideParams = z.infer<typeof decideParamsSchema>
export type DecideRequest = z.infer<typeof decideRequestSchema>
export type DecideResponse = z.infer<typeof decideResponseSchema>
export type DecideConfig = z.infer<typeof decideConfigBaseSchema>
export type DecisionQuestion = z.infer<typeof decisionQuestionSchema>
export type DecisionAnswer = z.infer<typeof decisionAnswerSchema>
