# Generate a Windows module-definition (.def) file that exports the qvac-fabric
# runtime surface (llama / ggml / common / mtmd) from the static libraries that
# are linked into qvac__fabric.bare. This mirrors the symbol allow-list applied
# by symbols.map (ELF version script) and exports.txt (Mach-O exported list) so
# consumer addons resolve the same llama/ggml/common API against the single
# shared runtime on every platform.
#
# This handles the *function* surface only. The few cross-DLL `common` data
# globals (build-info, log verbosity) are NOT exported: bare delay-loads sibling
# .bare modules on Windows, and delay-loading cannot resolve data imports (only
# functions get an IAT thunk). Consumers therefore define module-local copies of
# those globals (see each addon's windows_fabric_data.cpp). Data symbols are
# skipped below.
#
# Listing a symbol under EXPORTS acts as a reference, so the linker pulls the
# defining member out of the (non-whole-archived) static libraries on demand.
# Because the export list is generated by scanning those exact archives, every
# listed symbol is guaranteed to be present in the image, which avoids both the
# "unresolved export" errors of a hand-written .def and the duplicate-symbol
# risk of force-including whole archives.
#
# Matching is a substring test on the *linker* (mangled) symbol name, mirroring
# the Mach-O exports.txt patterns ("*common_*", "*string_*", ...). MSVC embeds
# the source identifiers literally in its decoration, so a member function such
# as common_init_result::model() decorates to "?model@common_init_result@@..."
# and is caught by the "common_" entry without needing to demangle. A single nm
# pass is therefore enough; the previous mangled/demangled pairing was fragile
# because the two passes do not emit a matching number of lines.
#
# Invoked at build time:
#   cmake -DNM=<llvm-nm> -DOUTPUT=<def> "-DINPUTS=<lib>|<lib>|..." \
#         -P generate-windows-def.cmake

if(NOT NM)
  message(FATAL_ERROR "generate-windows-def.cmake: -DNM=<llvm-nm> is required")
endif()
if(NOT OUTPUT)
  message(FATAL_ERROR "generate-windows-def.cmake: -DOUTPUT=<def> is required")
endif()

# Inputs are passed pipe-separated because a Windows path never contains '|',
# whereas ';' would be re-split into separate command arguments.
string(REPLACE "|" ";" _inputs "${INPUTS}")

# Source-level name fragments to export. Keep in sync with symbols.map /
# exports.txt. Matched as substrings of the decorated symbol name, so they catch
# both C entry points (bare "llama_decode") and C++ members/free functions whose
# decoration embeds the identifier (e.g. "?model@common_init_result@@...").
set(_allow
  "llama_" "llava_" "mtmd_" "ggml_" "gguf_"
  "common_" "json_schema_to_grammar" "string_"
  "set_process_priority" "postprocess_cpu_params" "metadata_handle_deleter")
string(JOIN "|" _alt ${_allow})
set(_pattern "(${_alt})")

set(_names "")

foreach(_input IN LISTS _inputs)
  if(NOT EXISTS "${_input}")
    continue()
  endif()

  execute_process(
    COMMAND "${NM}" --defined-only --extern-only --no-sort "${_input}"
    OUTPUT_VARIABLE _out
    RESULT_VARIABLE _rc)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "generate-windows-def.cmake: nm failed on ${_input} (${_rc})")
  endif()

  string(REPLACE "\r" "" _out "${_out}")
  string(REPLACE "\n" ";" _lines "${_out}")
  foreach(_line IN LISTS _lines)
    # nm lines are "<address> <type> <name>"; skip archive headers / blanks.
    if(NOT _line MATCHES "^[0-9A-Fa-f]+ ([A-Za-z]) (.+)$")
      continue()
    endif()
    set(_type "${CMAKE_MATCH_1}")
    set(_name "${CMAKE_MATCH_2}")

    # Export code symbols only (T/t text, W/w weak such as C++ template
    # instances). The cross-DLL `common` data globals (build-info, log verbosity)
    # are provided by module-local definitions in each consumer because bare
    # delay-loads this module and delay-loading cannot resolve data imports.
    if(NOT _type MATCHES "[TtWw]")
      continue()
    endif()
    if(NOT _name MATCHES "${_pattern}")
      continue()
    endif()
    list(APPEND _names "${_name}")
  endforeach()
endforeach()

# Dedup once at the end: a symbol can be defined in more than one archive, and
# duplicate EXPORTS entries would trigger linker warnings. REMOVE_DUPLICATES is
# far cheaper than an IN_LIST guard per symbol across these large archives.
list(REMOVE_DUPLICATES _names)

set(_body "")
foreach(_name IN LISTS _names)
  string(APPEND _body "    ${_name}\n")
endforeach()

file(WRITE "${OUTPUT}" "EXPORTS\n${_body}")
