server:
  url: "http://localhost:8080/run"
  batch_size: 20
  timeout: 300
  lib: "@tetherto/embed-llamacpp"
  version: "2.1.0"
  config:
    modelFilePath: "../../models/gte-large_fp16.gguf"
    addonConfig: "-ngl\t75"
dataset: ["ArguAna", "NFCorpus", "SciFact", "TRECCOVID","SCIDOCS"]
