"""Unit tests for tetherto.qvac_sdk.vla: preprocessing byte-parity against the JS
implementation, base64 tensor codecs, and the vlaRun/vlaHparams plugin-call
shapes over a fake transport.

fixtures/vla_reference.json holds input/output vectors generated by running
the SDK's own `vlaPreprocessImage`/`vlaPadState` (client/api/vla-helpers.ts)
on deterministic LCG inputs -- the Python port must reproduce those outputs
byte-for-byte, since the wire-format tensors must stay identical regardless
of where preprocessing runs.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from tetherto.qvac_sdk.vla import (
    VlaHparams,
    vla,
    vla_hparams,
    vla_pad_state,
    vla_preprocess_image,
)

REFERENCE = json.loads(
    (Path(__file__).parent / "fixtures" / "vla_reference.json").read_text()
)


def _f32(b64: str) -> np.ndarray:
    return np.frombuffer(base64.b64decode(b64), dtype="<f4")


def _u8(b64: str) -> np.ndarray:
    return np.frombuffer(base64.b64decode(b64), dtype="u1")


class FakeTransport:
    def __init__(self, response):
        self.response = response
        self.sent: Any = None

    async def call(self, payload):
        self.sent = payload
        return self.response

    async def call_stream(self, payload):
        raise NotImplementedError
        yield

    async def call_duplex(self, payload, up):
        raise NotImplementedError
        yield


# ---- byte-parity with the JS implementation --------------------------------


def test_preprocess_hwc_floats_matches_js_bytes():
    out = vla_preprocess_image(_f32(REFERENCE["case1_input"]), 8, 6, size=16)
    assert out.tobytes() == _f32(REFERENCE["case1_out"]).tobytes()


def test_preprocess_chw_uint8_matches_js_bytes():
    out = vla_preprocess_image(
        _u8(REFERENCE["case2_input"]), 5, 7, size=12, layout="chw"
    )
    assert out.tobytes() == _f32(REFERENCE["case2_out"]).tobytes()


def test_pad_state_matches_js_bytes():
    out = vla_pad_state([0.5, -1.25, 3], 8)
    assert out.tobytes() == _f32(REFERENCE["case3_out"]).tobytes()


# ---- preprocessing behavior --------------------------------------------------


def test_preprocess_letterboxes_bottom_right_with_minus_one_padding():
    # A wide solid-color frame: content lands bottom-right, top rows padded.
    width, height, size = 8, 4, 8
    pixels = np.full(width * height * 3, 128, dtype=np.uint8)
    out = vla_preprocess_image(pixels, width, height, size=size).reshape(3, size, size)
    new_h = int(height / (width / size))  # 4
    pad_top = size - new_h
    assert np.all(out[:, :pad_top, :] == -1)
    expected = 128 / 255 * 2 - 1
    assert np.allclose(out[:, pad_top:, :], expected, atol=1e-6)


def test_preprocess_scale_detection_leaves_unit_range_alone():
    pixels = np.full(4 * 4 * 3, 0.5, dtype=np.float32)
    out = vla_preprocess_image(pixels, 4, 4, size=4)
    # [0,1]-range floats aren't rescaled: 0.5 * 2 - 1 == 0.
    assert np.allclose(out, 0.0, atol=1e-6)


def test_preprocess_validates_inputs():
    with pytest.raises(ValueError, match="expected 48"):
        vla_preprocess_image(np.zeros(10, dtype=np.float32), 4, 4, size=4)
    with pytest.raises(TypeError, match="positive integers"):
        vla_preprocess_image(np.zeros(12, dtype=np.float32), -4, 1, size=4)


def test_pad_state_rejects_overflow_and_bad_target():
    with pytest.raises(ValueError, match="exceeds target_dim"):
        vla_pad_state([1.0] * 9, 8)
    with pytest.raises(TypeError, match="positive integer"):
        vla_pad_state([1.0], 0)


# ---- plugin-call marshaling ---------------------------------------------------


async def test_vla_encodes_tensors_and_decodes_actions():
    actions = np.array([0.25, -0.5, 1.5, 2.0], dtype="<f4")
    transport = FakeTransport(
        {
            "type": "pluginInvoke",
            "result": {
                "actions": base64.b64encode(actions.tobytes()).decode(),
                "actionDim": 2,
                "chunkSize": 2,
                "stats": {"total_ms": 12.5},
            },
        }
    )
    image = np.zeros(3 * 4 * 4, dtype=np.float32)
    result = await vla(
        transport,
        model_id="m-1",
        images=[image],
        img_width=4,
        img_height=4,
        state=[0.0, 1.0],
        tokens=[1, 2, 3],
        mask=[1, 1, 0],
        noise=np.zeros(4, dtype=np.float32),
    )
    assert np.array_equal(result.actions, actions)
    assert (result.action_dim, result.chunk_size) == (2, 2)
    assert result.stats == {"total_ms": 12.5}

    sent = transport.sent
    assert sent["handler"] == "vlaRun"
    wire = sent["params"]
    assert wire["type"] == "vlaRun"
    # Round-trip each encoded tensor back to verify dtype-faithful encoding.
    assert np.array_equal(
        np.frombuffer(base64.b64decode(wire["images"][0]), dtype="<f4"), image
    )
    assert np.array_equal(
        np.frombuffer(base64.b64decode(wire["state"]), dtype="<f4"),
        np.array([0.0, 1.0], dtype="<f4"),
    )
    assert np.array_equal(
        np.frombuffer(base64.b64decode(wire["tokens"]), dtype="<i4"),
        np.array([1, 2, 3], dtype="<i4"),
    )
    assert np.array_equal(
        np.frombuffer(base64.b64decode(wire["mask"]), dtype="u1"),
        np.array([1, 1, 0], dtype="u1"),
    )
    assert "noise" in wire


async def test_vla_hparams_parses_response():
    transport = FakeTransport(
        {
            "type": "pluginInvoke",
            "result": {
                "hparams": {
                    "chunkSize": 50,
                    "actionDim": 7,
                    "maxActionDim": 32,
                    "maxStateDim": 32,
                    "tokenizerMaxLength": 48,
                    "visionImageSize": 512,
                    "numCameras": 2,
                    "stateInputMode": "continuous",
                },
                "backendName": "Metal",
            },
        }
    )
    hparams, backend = await vla_hparams(transport, model_id="m-1")
    assert isinstance(hparams, VlaHparams)
    assert hparams.chunk_size == 50
    assert hparams.num_cameras == 2
    assert backend == "Metal"
    assert transport.sent["handler"] == "vlaHparams"
