import type { PlatformCalibration } from '@/resources/model-fit/types'

/**
 * android-arm64 coefficients.
 *
 * Generated by the calibration harness; see `METHODOLOGY.md` next to this
 * file for how the numbers are derived and validated.
 */
export const ANDROID_ARM64_CALIBRATION: PlatformCalibration = {
  weightUpperCoeff: 1.219,
  workingPeakBytes: {
    lower: 0,
    upper: 12047155
  },
  fixedOverheadBytes: {
    lower: 58216137,
    upper: 161649753
  },
  computeBufferBytesPerToken: {
    lower: 2282,
    upper: 3422
  },
  audioWindowBytes: {
    lower: 0,
    upper: 0
  },
  audioStreamingBytes: {
    lower: 0,
    upper: 0
  },
  validated: true,
  notes: [
    "weights were loaded with load_mode 'none' so RSS counted them in full at load; a mapped weight set keeps at most the artifact size resident, so weightUpperCoeff remains an upper bound for the default mmap load"
  ],
  measuredAt: '2026-09-06',
  measuredOn: {
    backend: 'cpu',
    kvElementBytes: 2
  }
}
