import type { PlatformCalibration } from '@/resources/model-fit/types'

/**
 * darwin-arm64 coefficients.
 *
 * Generated by `scripts/calibrate-model-fit.ts`; see `METHODOLOGY.md` next
 * to this file for how the numbers are derived and validated.
 */
export const DARWIN_ARM64_CALIBRATION: PlatformCalibration = {
  weightUpperCoeff: 1,
  fixedOverheadBytes: {
    lower: 5202537,
    upper: 68736841
  },
  computeBufferBytesPerToken: {
    lower: 0,
    upper: 0
  },
  audioWindowBytes: {
    lower: 0,
    upper: 0
  },
  audioStreamingBytes: {
    lower: 0,
    upper: 0
  },
  validated: true,
  measuredAt: '2026-08-31',
  measuredOn: {
    backend: 'metal',
    device: 'Apple M4 Pro',
    kvElementBytes: 1.0625
  }
}
