import type { PlatformCalibration } from '@/resources/model-fit/types'

/**
 * darwin-arm64 coefficients.
 *
 * Regenerated by `scripts/calibrate-model-fit.mjs`; see `METHODOLOGY.md` next
 * to this file for how the numbers are derived and validated.
 *
 * `validated: false` until a calibration run on real hardware clears the
 * held-out check, and an unvalidated platform assesses as `unknown` — the
 * placeholder numbers below are never used for a verdict. They exist so the
 * shape is reviewable and the harness has something to overwrite.
 */
export const DARWIN_ARM64_CALIBRATION: PlatformCalibration = {
  weightUpperCoeff: 1.05,
  fixedOverheadBytes: { lower: 128 * 1024 * 1024, upper: 512 * 1024 * 1024 },
  computeBufferBytesPerToken: { lower: 0, upper: 0 },
  audioWindowBytes: { lower: 0, upper: 0 },
  audioStreamingBytes: { lower: 0, upper: 0 },
  validated: false,
  notes: [
    'placeholder shape only — no measurements yet, so darwin-arm64 assesses as unknown',
    'run `bare scripts/calibrate-model-fit.mjs` on an Apple-silicon machine to replace this file'
  ]
}
