import type { PlatformCalibration } from '@/resources/model-fit/types'

/**
 * linux-x64-vulkan coefficients.
 *
 * Generated by `scripts/calibrate-model-fit.ts`; see `METHODOLOGY.md` next
 * to this file for how the numbers are derived and validated.
 */
export const LINUX_X64_VULKAN_CALIBRATION: PlatformCalibration = {
  weightUpperCoeff: 1.011,
  fixedOverheadBytes: {
    lower: 226824342,
    upper: 368029858
  },
  computeBufferBytesPerToken: {
    lower: 0,
    upper: 0
  },
  audioWindowBytes: {
    lower: 0,
    upper: 0
  },
  audioStreamingBytes: {
    lower: 0,
    upper: 0
  },
  validated: true,
  measuredAt: '2026-09-03',
  measuredOn: {
    backend: 'vulkan',
    device: 'NVIDIA RTX 4000 SFF Ada Generation',
    kvElementBytes: 1.0625
  }
}
