import type { PlatformCalibration } from '@/resources/model-fit/types'

/**
 * win32-x64 coefficients.
 *
 * Generated by `scripts/calibrate-model-fit.ts`; see `METHODOLOGY.md` next
 * to this file for how the numbers are derived and validated.
 */
export const WIN32_X64_CALIBRATION: PlatformCalibration = {
  weightUpperCoeff: 1,
  fixedOverheadBytes: {
    lower: 49636985,
    upper: 136840271
  },
  computeBufferBytesPerToken: {
    lower: 821,
    upper: 1232
  },
  audioWindowBytes: {
    lower: 0,
    upper: 0
  },
  audioStreamingBytes: {
    lower: 0,
    upper: 0
  },
  validated: true,
  notes: [
    "weights were loaded with load_mode 'none' so RSS counted them in full at load; a mapped weight set keeps at most the artifact size resident, so weightUpperCoeff remains an upper bound for the default mmap load"
  ],
  measuredAt: '2026-09-03',
  measuredOn: {
    backend: 'cpu',
    device: 'NVIDIA RTX 4000 SFF Ada Generation',
    kvElementBytes: 2
  }
}
