import RPC from "bare-rpc";
import type { Duplex, DuplexEvents } from "bare-stream";
import type { Worklet } from "react-native-bare-kit";
import { RPCConnectionFailedError } from "@/utils/errors-client";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.expo";
import { getClientLogger } from "@/logging";
import type { RuntimeContext } from "@/schemas";

const logger = getClientLogger();

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;
let workletInstance: Worklet | null = null;
let workletInitialized = false;
let cachedRuntimeContext: RuntimeContext | undefined;

logger.debug("EXPO RPC Client bundle");

async function getRuntimeContext(): Promise<RuntimeContext> {
  if (cachedRuntimeContext) {
    return cachedRuntimeContext;
  }

  // expo-device is optional - gracefully handle if not installed
  let deviceModel: string | undefined;
  let deviceBrand: string | undefined;
  let platform: "android" | "ios" | undefined;
  try {
    const expoModulesCore = await import("expo-modules-core");
    // this looks odd, but is necessary to ensure that import can be used safely.
    // It will crash the app if the module is not installed, but the node dependency is present.
    const nativeDeviceModule: unknown =
      expoModulesCore.requireOptionalNativeModule("ExpoDevice");
    if (nativeDeviceModule) {
      const Device = await import("expo-device");
      logger.info(
        `Device: ${Device.modelName} ${Device.brand} ${Device.osName}`,
      );
      const osName = Device?.osName?.toLowerCase();
      if (osName?.includes("ios")) {
        platform = "ios";
      } else if (osName?.includes("android")) {
        platform = "android";
      }
      deviceModel = Device.modelName ?? undefined;
      deviceBrand = Device.brand ?? undefined;
    }
  } catch {
    logger.debug("expo-device not available, device info will be omitted");
  }

  cachedRuntimeContext = {
    runtime: "react-native",
    platform,
    deviceModel,
    deviceBrand,
  };

  return cachedRuntimeContext;
}

export async function getRPC() {
  if (rpcInstance) {
    return rpcInstance;
  }

  if (rpcPromise) {
    return rpcPromise;
  }

  rpcPromise = (async () => {
    if (workletInstance) {
      logger.debug("🔄 Reusing existing worklet");
      rpcInstance = new RPC(
        workletInstance.IPC as unknown as Duplex<DuplexEvents>,
        () => {},
      );
      // Only initialize once per worklet - server state persists
      if (!workletInitialized) {
        const runtimeContext = await getRuntimeContext();
        await initializeConfig(rpcInstance, resolveConfig, runtimeContext);
        workletInitialized = true;
      }
      return rpcInstance;
    }

    const { Paths } = await import("expo-file-system");
    const bareKitModule = await import("react-native-bare-kit");

    const worklet = new bareKitModule.Worklet();
    workletInstance = worklet;
    logger.debug("Starting new worklet");

    // Load the mobile bundle - this will be generated by the Expo plugin
    // using the user's installed bare library versions
    let mobileBundle;
    try {
      // We need require here or the contents of the bundle will be interpreted as a module
      mobileBundle =
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        require("@qvac/sdk/worker.mobile.bundle") as unknown;
    } catch (error) {
      const message =
        "Failed to load mobile worker bundle. Make sure the QVAC Expo plugin is configured. " +
        `Add '@qvac/sdk/expo-plugin' to your app.json plugins array. ` +
        `Error: ${String(error)}`;
      logger.error(message);
      throw new RPCConnectionFailedError(
        message,
        error instanceof Error ? error : undefined,
      );
    }

    worklet.start("worker.bundle", mobileBundle as string, [
      // Normalize arg number across platforms
      "react-native-bare-kit",
      "worker.js",
      JSON.stringify({
        HOME_DIR: Paths.document.uri.replace("file://", ""),
      }),
    ]);
    logger.info("Worklet started");
    rpcInstance = new RPC(
      worklet.IPC as unknown as Duplex<DuplexEvents>,
      () => {
        // Use this for async callbacks
      },
    );

    const runtimeContext = await getRuntimeContext();
    await initializeConfig(rpcInstance, resolveConfig, runtimeContext);
    workletInitialized = true;

    return rpcInstance;
  })();

  try {
    return await rpcPromise;
  } catch (error) {
    logger.error(`Failed to initialize RPC: ${String(error)}`);
    throw error;
  } finally {
    rpcPromise = null;
  }
}

export function close() {
  logger.info("🧹 Closing RPC client (Expo)");
  rpcInstance = null;
  rpcPromise = null;
}
