import RPC from "bare-rpc";
import type { Duplex, DuplexEvents } from "bare-stream";
import { RPCConnectionFailedError } from "@/utils/errors-client";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.expo";
import { getClientLogger } from "@/logging";

const logger = getClientLogger();

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;

logger.debug("EXPO RPC Client bundle");

export async function getRPC() {
  if (rpcInstance) {
    return rpcInstance;
  }

  if (rpcPromise) {
    return rpcPromise;
  }

  rpcPromise = (async () => {
    const { Paths } = await import("expo-file-system");
    const bareKitModule = await import("react-native-bare-kit");

    const worklet = new bareKitModule.Worklet();
    logger.debug("Starting worklet");

    // Load the mobile bundle - this will be generated by the Expo plugin
    // using the user's installed bare library versions
    let mobileBundle;
    try {
      // We need require here or the contents of the bundle will be interpreted as a module
      mobileBundle =
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        require("@qvac/sdk/worker.mobile.bundle") as unknown;
    } catch (error) {
      const message =
        "Failed to load mobile worker bundle. Make sure the QVAC Expo plugin is configured. " +
        `Add '@qvac/sdk/expo-plugin' to your app.json plugins array. ` +
        `Error: ${String(error)}`;
      logger.error(message);
      throw new RPCConnectionFailedError(
        message,
        error instanceof Error ? error : undefined,
      );
    }

    worklet.start("worker.bundle", mobileBundle as string, [
      // Normalize arg number across platforms
      "react-native-bare-kit",
      "worker.js",
      JSON.stringify({
        HOME_DIR: Paths.document.uri.replace("file://", ""),
      }),
    ]);
    logger.info("Worklet started");
    rpcInstance = new RPC(
      worklet.IPC as unknown as Duplex<DuplexEvents>,
      () => {
        // Use this for async callbacks
      },
    );

    await initializeConfig(rpcInstance, resolveConfig);

    return rpcInstance;
  })();

  try {
    return await rpcPromise;
  } catch (error) {
    logger.error(`Failed to initialize RPC: ${String(error)}`);
    throw error;
  } finally {
    rpcPromise = null;
  }
}

export function close() {
  logger.info("🧹 Closing RPC client (Expo)");
  rpcInstance = null;
  rpcPromise = null;
}
