import RPC from "bare-rpc";
import spawn, {
  type ChildProcess as BareChildProcess,
} from "bare-runtime/spawn";
import type { Duplex, DuplexEvents } from "bare-stream";
import { createServer } from "node:net";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RPCRequestNotSentError } from "@/utils/errors-client";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.node";
import { getClientLogger } from "@/logging";
import type { RuntimeContext } from "@/schemas";

const logger = getClientLogger();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;
let bareWorkerProc: BareChildProcess | null = null;
let ipcServer: ReturnType<typeof createServer> | null = null;

/**
 * Find project root by looking for package.json (sync version)
 * Safe to call at module load time
 */
function findProjectRootSync(): string | undefined {
  let dir = process.cwd();
  const root = path.parse(dir).root;

  while (dir !== root) {
    if (fs.existsSync(path.join(dir, "package.json"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }

  return undefined;
}

function getResourcesPathSync(): string | undefined {
  const { resourcesPath } = process as { resourcesPath?: string };
  return typeof resourcesPath === "string" ? resourcesPath : undefined;
}

function resolvePackagedWorkerPath(): string | undefined {
  const resourcesPath = getResourcesPathSync();
  if (!resourcesPath) return undefined;

  const candidates = [
    path.join(resourcesPath, "app.asar.unpacked", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "app", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "qvac", "worker.entry.mjs"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }

  return undefined;
}

/**
 * Get default worker path from SDK dist
 */
function getDefaultWorkerPath(): string {
  const packagedWorker = path.resolve(__dirname, "../../server/worker.js");
  if (fs.existsSync(packagedWorker)) return packagedWorker;

  // Dev/source layout fallback
  return path.resolve(__dirname, "../../dist/server/worker.js");
}

/**
 * Resolve worker path with priority:
 * 1. qvac/worker.entry.mjs in project root (generated by npx qvac bundle sdk)
 * 2. Default SDK worker
 */
function resolveWorkerPath(): string {
  const envWorkerPath = process.env["QVAC_WORKER_PATH"] as string | undefined;
  if (envWorkerPath) {
    const normalized = path.resolve(envWorkerPath);
    if (fs.existsSync(normalized)) {
      logger.info(`🔧 Using worker entry from QVAC_WORKER_PATH: ${normalized}`);
      return normalized;
    }
    logger.warn(
      `⚠️ QVAC_WORKER_PATH was set but file was not found: ${normalized}. Falling back.`,
    );
  }

  // Prefer packaged worker entry when running as a packaged Electron app.
  // This avoids accidental coupling to the developer's cwd, and ensures the
  // bare worker reads JS modules from the filesystem (not app.asar).
  const packagedWorker = resolvePackagedWorkerPath();
  if (packagedWorker) {
    logger.info(`🔧 Using packaged worker entry: ${packagedWorker}`);
    return packagedWorker;
  }

  // 1. Check for custom worker entry at project root
  // Note: We use worker.entry.mjs (unbundled ESM) for desktop because bare can
  // load ES modules directly. The packed bundle is for mobile only.
  const projectRoot = findProjectRootSync();
  if (projectRoot) {
    const customEntry = path.join(projectRoot, "qvac", "worker.entry.mjs");
    if (fs.existsSync(customEntry)) {
      logger.info(`🔧 Using custom worker entry: ${customEntry}`);
      return customEntry;
    }
  }

  // 2. Fallback to default SDK worker
  const defaultPath = getDefaultWorkerPath();
  logger.debug(`🔧 Using default SDK worker: ${defaultPath}`);
  return defaultPath;
}

const WORKER_PATH = resolveWorkerPath();

const SOCKET_PATH =
  process.platform === "win32"
    ? `\\\\.\\pipe\\qvac-worker-${process.pid}`
    : path.join(os.tmpdir(), `qvac-worker-${process.pid}.sock`);

async function ensureRPC(): Promise<RPC> {
  if (rpcInstance) return rpcInstance;
  if (rpcPromise) return rpcPromise;

  rpcPromise = new Promise((resolve, reject) => {
    ipcServer = createServer((socket) => {
      rpcInstance = new RPC(
        socket as unknown as Duplex<DuplexEvents>,
        () => {},
      );
      resolve(rpcInstance);
    });

    ipcServer.on("error", reject);

    ipcServer.listen(SOCKET_PATH, () => {
      bareWorkerProc = spawn("bare", {
        args: [
          WORKER_PATH,
          JSON.stringify({
            QVAC_IPC_SOCKET_PATH: SOCKET_PATH,
            HOME_DIR: os.homedir(),
          }),
        ],
        stdio: ["inherit", "inherit", "inherit"],
      });
    });
  });

  const rpc = await rpcPromise;

  const runtimeContext: RuntimeContext = {
    runtime: "node",
    platform: process.platform as "darwin" | "linux" | "win32",
  };
  await initializeConfig(rpc, resolveConfig, runtimeContext);

  return rpc;
}

const mockRPC = {
  request: (command: number) => {
    let sentData: { data: string; encoding: BufferEncoding } | null = null;

    return {
      send: (data: string, encoding: BufferEncoding) => {
        sentData = { data, encoding };
      },

      reply: async (encoding: BufferEncoding): Promise<Buffer> => {
        if (!sentData) {
          throw new RPCRequestNotSentError();
        }

        const rpc = await ensureRPC();
        const req = rpc.request(command);
        req.send(
          sentData.data,
          sentData.encoding as "utf-8" | "ascii" | "binary",
        );

        const response = await req.reply(
          encoding as "utf-8" | "ascii" | "binary",
        );
        return Buffer.isBuffer(response)
          ? response
          : Buffer.from(typeof response === "string" ? response : "", encoding);
      },

      createResponseStream: async function* () {
        if (!sentData) {
          throw new RPCRequestNotSentError();
        }

        const rpc = await ensureRPC();
        const req = rpc.request(command);
        req.send(
          sentData.data,
          sentData.encoding as "utf-8" | "ascii" | "binary",
        );
        const stream = req.createResponseStream({
          encoding: sentData.encoding as "utf-8" | "ascii" | "binary",
        });

        for await (const chunk of stream) {
          yield chunk;
        }
      },
    };
  },
};

export function getRPC() {
  return mockRPC;
}

export function close() {
  logger.info("🧹 Closing RPC client");
  if (bareWorkerProc) {
    logger.info("🐻🔫 Killing bare worker process");
    bareWorkerProc.kill("SIGTERM");
    bareWorkerProc = null;
  }
  if (ipcServer) {
    logger.info("🔌 Closing IPC server");
    ipcServer.close();
    ipcServer = null;
  }
  rpcInstance = null;
  rpcPromise = null;
}

// Register cleanup handlers for the parent process
process.once("exit", close);
