// .source is generated by fumadocs-mdx at build time (see next.config.mjs)
import { docs, meta } from '../../.source/index.js';
import { createMDXSource } from 'fumadocs-mdx';
import { loader } from 'fumadocs-core/source';

export const source = loader({
  baseUrl: '/docs',
  source: createMDXSource(docs, meta),
});
