import QvacError = require("@qvac/error");
declare const QvacErrorBase: typeof QvacError.QvacErrorBase;
export declare class QvacErrorAddonWhisper extends QvacErrorBase {
}
export declare const ERR_CODES: Readonly<{
    FAILED_TO_LOAD_WEIGHTS: 6001;
    FAILED_TO_CANCEL: 6002;
    FAILED_TO_APPEND: 6003;
    FAILED_TO_GET_STATUS: 6004;
    FAILED_TO_DESTROY: 6005;
    FAILED_TO_ACTIVATE: 6006;
    FAILED_TO_RESET: 6007;
    FAILED_TO_PAUSE: 6008;
    VAD_MODEL_REQUIRED: 6009;
    JOB_ALREADY_RUNNING: 6010;
    INVALID_AUDIO_INPUT: 6011;
    FAILED_TO_START_STREAMING: 6012;
    FAILED_TO_APPEND_STREAMING: 6013;
    FAILED_TO_END_STREAMING: 6014;
    BUFFER_LIMIT_EXCEEDED: 6015;
    FAILED_TO_STOP: 6016;
    MODEL_REQUIRED: 6017;
    VAD_MODEL_NOT_FOUND: 6018;
}>;
export {};
