// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./map-addon-event.test.js')
  await import('./signal-forwarding.test.js')

  test.resume()
}
