#!/usr/bin/env bash
#
# .agent/setup.sh — Configure agent tooling for Claude Code and/or Cursor
#
# Usage: .agent/setup.sh [claude|cursor|all]
#
# Copies the opt-in OCR agent framework from .agent/ into agent-specific
# directories. Repository-wide skills are configured separately.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

HEADER="<!-- AUTO-GENERATED by .agent/setup.sh — do not edit directly. Edit the source in .agent/ instead. -->"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
copy_with_header() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  printf '%s\n\n' "$HEADER" > "$dst"
  cat "$src" >> "$dst"
  echo "  copied: $dst"
}

copy_plain() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "  copied: $dst"
}

copy_skills() {
  local source_root="$1"
  local target_root="$2"
  local skill_name
  local rel

  for skill_dir in "$source_root"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    [ -f "$skill_dir/SKILL.md" ] || continue

    copy_plain "$skill_dir/SKILL.md" "$target_root/$skill_name/SKILL.md"
    find "$skill_dir" -type f ! -name "SKILL.md" | while read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$target_root/$skill_name/$rel"
    done
  done
}

verify_skill_names_do_not_overlap() {
  local repository_root="$1"
  local package_root="$2"
  local skill_name

  for skill_dir in "$package_root"/*/; do
    [ -f "$skill_dir/SKILL.md" ] || continue
    skill_name="$(basename "$skill_dir")"
    if [ -f "$repository_root/$skill_name/SKILL.md" ]; then
      echo "Error: skill '$skill_name' exists in both $repository_root and $package_root" >&2
      return 1
    fi
  done
}

strip_yaml_frontmatter() {
  # Remove YAML frontmatter (--- ... ---) from the beginning of a file
  awk '
    BEGIN { in_front=0; found=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { in_front=0; found=1; next }
    in_front { next }
    found && NR>1 && /^\s*$/ && !printed { next }
    { printed=1; print }
  ' "$1"
}

wrap_with_frontmatter() {
  local src="$1"
  local name="$2"
  local description="$3"
  local dst="$4"
  mkdir -p "$(dirname "$dst")"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$description"
    cat "$src"
  } > "$dst"
  echo "  copied: $dst (with frontmatter)"
}

wrap_mdc_rule() {
  local src="$1"
  local description="$2"
  local always_apply="$3"
  local dst="$4"
  mkdir -p "$(dirname "$dst")"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: %s\n---\n\n' "$description" "$always_apply"
    cat "$src"
  } > "$dst"
  echo "  generated: $dst"
}

extract_frontmatter_field() {
  local file="$1"
  local field="$2"
  awk -v f="$field" '
    BEGIN { in_front=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { exit }
    in_front && $0 ~ "^"f":" {
      sub("^"f":[ ]*", "")
      gsub(/^"/, ""); gsub(/"$/, "")
      print
      exit
    }
  ' "$file"
}

generate_cursor_agent_rule() {
  local src="$1"
  local dst="$2"
  local agent_name
  agent_name="$(extract_frontmatter_field "$src" "name")"
  local description="Agent prompt: ${agent_name} — use as context when launching Task sub-agents"
  local body
  body="$(strip_yaml_frontmatter "$src")"

  mkdir -p "$(dirname "$dst")"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\ndescription: %s\nalwaysApply: false\n---\n\n' "$description"
    printf '%s\n' "$body" \
      | sed 's|`\.claude/agent-conduct\.md`|the agent conduct rules (`.cursor/rules/agent-conduct.mdc`)|g'
  } > "$dst"
  echo "  generated: $dst"
}


# ---------------------------------------------------------------------------
# Setup: Claude Code
# ---------------------------------------------------------------------------
setup_claude() {
  echo ""
  echo "Setting up Claude Code (.claude/)..."

  # Conduct
  copy_with_header "$SCRIPT_DIR/conduct.md" "$REPO_ROOT/.claude/agent-conduct.md"

  # Knowledge
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "$REPO_ROOT/.claude/knowledge/$(basename "$f")"
  done

  # Package-specific OCR skills are copied as an additional layer.
  copy_skills "$SCRIPT_DIR/skills" "$REPO_ROOT/.claude/skills"

  # Agents
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    copy_plain "$f" "$REPO_ROOT/.claude/agents/$(basename "$f")"
  done

  # Settings
  if [ -f "$SCRIPT_DIR/settings.json" ]; then
    copy_plain "$SCRIPT_DIR/settings.json" "$REPO_ROOT/.claude/settings.json"
  fi

  # MCP: print instructions (Claude Code uses user-level config)
  echo ""
  echo "  MCP servers are defined in .agent/mcp.json."
  echo "  To configure Claude Code, add them to ~/.claude/settings.json under 'mcpServers'."
  echo "  See .agent/mcp.json for the server definitions."
  echo ""
  echo "Claude Code setup complete."
}

# ---------------------------------------------------------------------------
# Setup: Cursor
# ---------------------------------------------------------------------------
setup_cursor() {
  echo ""
  echo "Setting up Cursor (.cursor/)..."

  # Conduct → always-applied .mdc rule
  wrap_mdc_rule \
    "$SCRIPT_DIR/conduct.md" \
    "Agent Code of Conduct — scope, quality gates, retry policy, Asana updates, code style, CI validation, and prohibited actions" \
    "true" \
    "$REPO_ROOT/.cursor/rules/agent-conduct.mdc"

  # Knowledge → requestable .mdc rules
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    desc="$(head -1 "$f" | sed 's/^# //')"
    wrap_mdc_rule "$f" "$desc" "false" "$REPO_ROOT/.cursor/rules/knowledge/$name.mdc"
  done

  # Agents → requestable .mdc rules (stripped of Claude-specific frontmatter)
  for f in "$SCRIPT_DIR"/agents/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f" .md)"
    generate_cursor_agent_rule "$f" "$REPO_ROOT/.cursor/rules/agents/$name.mdc"
  done


  # Cursor discovers repository skills directly from .agents/skills. Only the
  # package-specific OCR skills need generated compatibility copies.
  copy_skills "$SCRIPT_DIR/skills" "$REPO_ROOT/.cursor/skills"

  # MCP: generate .cursor/mcp.json from .agent/mcp.json
  # Cursor uses mcpServers at the top level (not nested under "servers")
  node -e "
    const src = require('$SCRIPT_DIR/mcp.json');
    const out = { mcpServers: src.servers };
    process.stdout.write(JSON.stringify(out, null, 2) + '\n');
  " > "$REPO_ROOT/.cursor/mcp.json"
  echo "  generated: .cursor/mcp.json"

  echo ""
  echo "Cursor setup complete."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
target="${1:-all}"

verify_skill_names_do_not_overlap \
  "$REPO_ROOT/.agents/skills" \
  "$SCRIPT_DIR/skills"

echo "=== Agent Config Setup ==="
echo "Source: .agent/"
echo "Target: $target"

case "$target" in
  claude)
    setup_claude
    ;;
  cursor)
    setup_cursor
    ;;
  all)
    setup_claude
    setup_cursor
    ;;
  *)
    echo "Usage: .agent/setup.sh [claude|cursor|all]"
    exit 1
    ;;
esac

echo ""
echo "Done. Edit repository skills in .agents/skills and OCR-specific sources in packages/ocr-ggml/.agent/."
