import { promises as fsp } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import semver from 'semver'
import {
  fetchBareKitVersionFromGitHub,
  fetchBareVersionFromGitHub,
  fetchText,
  REACT_NATIVE_BARE_KIT
} from '@/commands/verify/bare-kit-runtime'
import {
  BARE_KIT_BARE_VERSIONS,
  REACT_NATIVE_BARE_KIT_RUNTIMES,
  type BareKitRuntime
} from '@/commands/verify/bare-kit-runtimes'

const CONCURRENCY = 8

const OUTPUT_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'commands',
  'verify',
  'bare-kit-runtimes.ts'
)

async function listPublishedVersions() {
  const packument = JSON.parse(
    await fetchText(`https://registry.npmjs.org/${REACT_NATIVE_BARE_KIT}`)
  ) as { versions: Record<string, unknown> }
  return Object.keys(packument.versions)
}

async function listBareKitTags() {
  const tags = JSON.parse(
    await fetchText('https://api.github.com/repos/holepunchto/bare-kit/tags?per_page=100')
  ) as Array<{ name: string }>
  return tags.map((tag) => tag.name.replace(/^v/, ''))
}

function latest(versions: string[]) {
  const valid = versions.filter((version) => semver.valid(version) !== null)
  return valid.length === 0 ? null : valid.sort(semver.rcompare)[0]!
}

/**
 * Releases newer than the newest one already in the table, oldest first.
 * Everything at or below it was probed on an earlier run, including the old
 * react-native-bare-kit releases that have no CMakeLists.txt to parse.
 */
function newerThan(versions: string[], lastKnown: string | null) {
  return versions
    .filter((version) => semver.valid(version) !== null)
    .filter((version) => lastKnown === null || semver.gt(version, lastKnown))
    .sort(semver.compare)
}

async function mapConcurrent<T, R>(items: T[], fn: (item: T) => Promise<R>) {
  const results: R[] = new Array(items.length)
  let next = 0
  async function worker() {
    while (next < items.length) {
      const index = next++
      results[index] = await fn(items[index]!)
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker))
  return results
}

async function tryFetch(fn: () => Promise<string | null>) {
  try {
    return await fn()
  } catch {
    return null
  }
}

function sortedEntries<T>(record: Record<string, T>) {
  return Object.entries(record).sort(([a], [b]) => semver.compare(a, b))
}

function render(runtimes: Record<string, BareKitRuntime>, bareByBareKit: Record<string, string>) {
  const lines = [
    '// Generated by scripts/generate-bare-kit-runtimes.ts. Do not edit by hand.',
    '',
    'export interface BareKitRuntime {',
    '  bareKit: string',
    '  bare: string',
    '}',
    '',
    '/**',
    ' * react-native-bare-kit releases whose CMakeLists.txt names the bare-kit',
    ' * prebuilds it ships. Older releases carry no such reference.',
    ' */',
    'export const REACT_NATIVE_BARE_KIT_RUNTIMES: Record<string, BareKitRuntime> = {'
  ]
  lines.push(
    ...entryLines(
      sortedEntries(runtimes).map(
        ([version, runtime]) =>
          `'${version}': { bareKit: '${runtime.bareKit}', bare: '${runtime.bare}' }`
      )
    )
  )
  lines.push('}', '', '/** Bare version each bare-kit release is built against. */')
  lines.push('export const BARE_KIT_BARE_VERSIONS: Record<string, string> = {')
  lines.push(
    ...entryLines(sortedEntries(bareByBareKit).map(([bareKit, bare]) => `'${bareKit}': '${bare}'`))
  )
  lines.push('}', '')
  return lines.join('\n')
}

/** Object entries in the repo's Prettier style: no trailing comma. */
function entryLines(entries: string[]) {
  return entries.map((entry, index) => `  ${entry}${index === entries.length - 1 ? '' : ','}`)
}

async function main() {
  const full = process.argv.includes('--full')
  const bareByBareKit: Record<string, string> = full ? {} : { ...BARE_KIT_BARE_VERSIONS }
  const runtimes: Record<string, BareKitRuntime> = full ? {} : { ...REACT_NATIVE_BARE_KIT_RUNTIMES }

  const bareKitTags = newerThan(await listBareKitTags(), latest(Object.keys(bareByBareKit)))
  console.log(`Resolving ${bareKitTags.length} new bare-kit releases...`)
  const bareVersions = await mapConcurrent(bareKitTags, (bareKit) =>
    tryFetch(() => fetchBareVersionFromGitHub(bareKit))
  )
  bareKitTags.forEach((bareKit, index) => {
    const bare = bareVersions[index]
    if (bare) bareByBareKit[bareKit] = bare
  })

  const versions = newerThan(await listPublishedVersions(), latest(Object.keys(runtimes)))
  console.log(`Resolving ${versions.length} new ${REACT_NATIVE_BARE_KIT} releases...`)
  const bareKitByVersion = await mapConcurrent(versions, (version) =>
    tryFetch(() => fetchBareKitVersionFromGitHub(version))
  )
  versions.forEach((version, index) => {
    const bareKit = bareKitByVersion[index]
    const bare = bareKit ? bareByBareKit[bareKit] : undefined
    if (bareKit && bare) runtimes[version] = { bareKit, bare }
  })

  await fsp.writeFile(OUTPUT_PATH, render(runtimes, bareByBareKit))
  console.log(
    `Wrote ${Object.keys(runtimes).length} ${REACT_NATIVE_BARE_KIT} and ` +
      `${Object.keys(bareByBareKit).length} bare-kit entries to ${OUTPUT_PATH}`
  )
}

await main()
