#!/usr/bin/env node
// Restores packages/cli/package.json to its committed state and re-runs
// `npm install`. Use after `npm run dev:link` (or any other ad-hoc local
// dep swap) when you want to get back to the canonical `file:../sdk` wiring
// before committing.
//
// The committed state is the source of truth for what `npm publish` checks
// (see scripts/check-publish-ready.cjs), so pinning the unlink target here
// would just drift out of sync. `git checkout HEAD` is always correct.
//
// package-lock.json is gitignored in this package, so it's regenerated by
// the trailing `npm install` rather than checked out.

'use strict'

const path = require('node:path')
const readline = require('node:readline')
const { spawnSync } = require('node:child_process')

const CLI_DIR = path.resolve(__dirname, '..')
const FILES = ['package.json']

function run (cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    cwd: CLI_DIR,
    stdio: 'inherit',
    ...opts
  })
  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

function prompt (question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    })
    rl.question(question, (answer) => {
      rl.close()
      resolve(answer)
    })
  })
}

async function main () {
  console.log(
    'dev:unlink will restore packages/cli/package.json to its committed state\n' +
    'and re-run `npm install` (regenerating package-lock.json).\n'
  )

  if (process.stdin.isTTY && !process.env['DEV_UNLINK_YES']) {
    const answer = await prompt('Continue? [y/N] ')
    if (!/^y(es)?$/i.test(answer.trim())) {
      console.log('Aborted.')
      process.exit(0)
    }
  }

  run('git', ['checkout', 'HEAD', '--', ...FILES])
  run('npm', ['install'])
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
