/**
 * Shared helpers for the addon CI runner-label catalog.
 *
 * Source of truth: .github/runners.yaml
 * Generated consumer: .github/workflows/reusable-runner-names.yml
 */
import { readdirSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
export const repoRoot = resolve(here, '../../..')

export const RUNNERS_YAML = '.github/runners.yaml'
export const REUSABLE_WORKFLOW = '.github/workflows/reusable-runner-names.yml'
export const ACTIONLINT_YAML = '.github/actionlint.yaml'
export const REUSABLE_USES = './.github/workflows/reusable-runner-names.yml'

const ADDON_PREFIXES = [
  'integration-test-',
  'integration-mobile-test-',
  'cpp-tests-',
  'cpp-test-coverage-',
  'pr-test-inference-addon',
]

const ADDON_EXACT = new Set([
  'reusable-prebuilds.yml',
  'reusable-cpp-tests-translation-nmtcpp.yml',
])

const ENTRY_RE = /^([a-z][a-z0-9_]*):\s+(\S+)\s*(?:#\s*(.*\S))?\s*$/

/**
 * Deliberately a line parser, NOT a YAML parser. `.github/runners.yaml` is a
 * flat `key: label # comment` list by contract (stated in its header), which
 * keeps this dependency-free. Anything outside that shape fails loudly here
 * rather than silently mis-parsing: indented / nested lines and bare junk do
 * not match ENTRY_RE and throw; quoted or list/map values are rejected below.
 * If runners.yaml ever needs real YAML (nesting, anchors), swap this for a YAML
 * library at the same time — do not just relax the regex.
 */
export function parseRunnersYaml(source) {
  const runners = []
  const seenKeys = new Set()
  const seenLabels = new Set()

  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const match = line.match(ENTRY_RE)
    if (!match) {
      throw new Error(`invalid runners.yaml line (expected "key: label # comment"): ${JSON.stringify(line)}`)
    }
    const [, key, label, description = ''] = match
    if (/["'{}[\]]/.test(label)) {
      throw new Error(`runners.yaml value must be a bare label, not quoted/structured: ${JSON.stringify(line)}`)
    }
    if (seenKeys.has(key)) throw new Error(`duplicate runner key: ${key}`)
    if (seenLabels.has(label)) throw new Error(`duplicate runner label: ${label}`)
    seenKeys.add(key)
    seenLabels.add(label)
    runners.push({ key, label, description })
  }

  if (runners.length === 0) throw new Error('runners.yaml has no entries')
  return runners
}

export function loadRunners() {
  return parseRunnersYaml(readFileSync(join(repoRoot, RUNNERS_YAML), 'utf8'))
}

export function labelToKey(runners) {
  return new Map(runners.map((entry) => [entry.label, entry.key]))
}

/** Longest labels first so qvac-ubuntu2204-x64-gpu wins over qvac-ubuntu2204-x64. */
export function labelsLongestFirst(runners) {
  return [...runners].sort((a, b) => b.label.length - a.label.length)
}

export function listAddonWorkflows() {
  const directory = join(repoRoot, '.github/workflows')
  return readdirSync(directory)
    .filter((name) => name.endsWith('.yml') || name.endsWith('.yaml'))
    .filter((name) => ADDON_EXACT.has(name) || ADDON_PREFIXES.some((prefix) => name.startsWith(prefix)))
    .map((name) => `.github/workflows/${name}`)
    .sort()
}

export function renderReusableWorkflow(runners) {
  const outputBlock = runners
    .map((entry) => {
      const description = entry.description || `Runner label ${entry.label}`
      return [
        `      ${entry.key}:`,
        `        description: ${yamlDoubleQuoted(description)}`,
        `        value: \${{ jobs.export.outputs.${entry.key} }}`,
      ].join('\n')
    })
    .join('\n')

  const jobOutputs = runners
    .map((entry) => `      ${entry.key}: \${{ steps.export.outputs.${entry.key} }}`)
    .join('\n')

  const exportLines = runners
    .map((entry) => `          echo "${entry.key}=${entry.label}" >> "$GITHUB_OUTPUT"`)
    .join('\n')

  return `# AUTO-GENERATED by .github/scripts/sync-runner-names.mjs
# Source of truth: ${RUNNERS_YAML}
# Do not edit this file by hand.

name: Runner names

on:
  workflow_call:
    outputs:
${outputBlock}

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
${jobOutputs}
    steps:
      - name: Export runner labels
        id: export
        run: |
${exportLines}
`
}

function yamlDoubleQuoted(value) {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

export function stripYamlComments(line) {
  let inSingle = false
  let inDouble = false
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (ch === "'" && !inDouble) inSingle = !inSingle
    else if (ch === '"' && !inSingle && line[i - 1] !== '\\') inDouble = !inDouble
    else if (ch === '#' && !inSingle && !inDouble) return line.slice(0, i)
  }
  return line
}

function isCommentLine(line) {
  return /^\s*#/.test(line)
}

/**
 * Flags catalog labels hardcoded where they select the machine: `runs-on:`,
 * matrix `runner:` fields, `"runner":"<label>"` inside fromJSON matrix blobs,
 * and catalog labels quoted inside a `runs-on:` / `runner:` `${{ }}` expression
 * (e.g. a regression that inlines `${{ cond && 'macos-14' || 'qvac-...' }}`
 * instead of going through `needs.runner_names.outputs.*`).
 *
 * `os:` matrix values, `matrix.os == '<label>'` conditionals, and `"os":"..."`
 * in fromJSON blobs are deliberately NOT flagged. `os` is a frozen logical
 * identity that names a matrix row / gates steps / labels artifacts; it is
 * decoupled from the runner catalog (self-hosted rows pair e.g. `os: macos-14`
 * with `runner: qvac-macos26-arm64-gpu`). Every catalog-label `os` row already
 * carries an explicit `runner:` from the catalog, so `runs-on` never resolves
 * via a `matrix.os` fallback. Bumping a catalog label therefore never needs an
 * `os` edit, and vice versa. See docs/ci/SELF-HOSTED-RUNNERS.md ("os is a frozen
 * logical id"). Do not fold `os` in here without also renaming the label-like
 * `os` values, or every intentional identity becomes a false positive.
 */
export function findHardcodedLabelViolations(relativePath, source, runners) {
  const findings = []
  const lines = source.split(/\r?\n/)
  const labels = labelsLongestFirst(runners)

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (isCommentLine(line)) continue
    const code = stripYamlComments(line)

    // A `runs-on:` / `runner:` assignment whose value is a `${{ }}` expression:
    // any catalog label quoted inside it selects the machine and must come from
    // the catalog outputs, never an inline literal (covers the mobile ternary).
    const runnerExpr =
      /^\s+(?:-\s+)?(?:runs-on|runner):\s+.*\$\{\{.*\}\}/.test(code)

    for (const { label } of labels) {
      const escaped = label.replaceAll('.', '\\.')
      const patterns = [
        new RegExp(`^\\s+runs-on:\\s+${escaped}\\s*$`),
        new RegExp(`^\\s+(?:-\\s+)?runner:\\s+${escaped}\\s*$`),
        new RegExp(`"runner"\\s*:\\s*"${escaped}"`),
      ]
      // Quoted catalog label inside a runs-on/runner `${{ }}` expression —
      // covers both `runs-on: ${{ '<label>' }}` and the mobile ternary.
      const quotedInRunnerExpr =
        runnerExpr && new RegExp(`['"]${escaped}['"]`).test(code)
      if (quotedInRunnerExpr || patterns.some((pattern) => pattern.test(code))) {
        findings.push({
          file: relativePath,
          line: i + 1,
          label,
          text: line.trim(),
        })
        break
      }
    }
  }

  return findings
}

export function hasRunnerNamesJob(source) {
  return (
    /^\s+runner_names:\s*$/m.test(source) &&
    source.includes(`uses: ${REUSABLE_USES}`)
  )
}

export function findMissingRunnerNamesNeeds(relativePath, source) {
  if (!source.includes('needs.runner_names.outputs')) return []
  if (hasRunnerNamesJob(source)) return []
  return [
    {
      file: relativePath,
      message: `references needs.runner_names.outputs but has no runner_names job using ${REUSABLE_USES}`,
    },
  ]
}

export function findJobsMissingNeeds(relativePath, source) {
  if (!source.includes('needs.runner_names.outputs')) return []
  const findings = []
  const jobs = splitJobs(source)
  for (const job of jobs) {
    if (job.id === 'runner_names') continue
    if (!job.body.includes('needs.runner_names.outputs')) continue
    if (jobHasRunnerNamesNeed(job.body)) continue
    findings.push({
      file: relativePath,
      job: job.id,
      message: `job "${job.id}" uses needs.runner_names.outputs but does not list runner_names in needs`,
    })
  }
  return findings
}

/**
 * The runner_names bootstrap job calls a reusable workflow; a reusable-calling
 * job with no permissions block inherits broad defaults (flagged by the
 * workflow-security audit and forbidden by the DevOps GHA rule). Require an
 * explicit permissions block on it.
 */
export function findRunnerNamesMissingPermissions(relativePath, source) {
  const job = splitJobs(source).find((entry) => entry.id === 'runner_names')
  if (!job) return []
  if (/^    permissions:\s*$/m.test(job.body) || /^    permissions:\s*\{/m.test(job.body)) {
    return []
  }
  return [
    {
      file: relativePath,
      message: 'runner_names job must declare an explicit permissions block (e.g. contents: read)',
    },
  ]
}

function jobHasRunnerNamesNeed(body) {
  if (/^    needs:\s+runner_names\s*$/m.test(body)) return true
  if (/^      - runner_names\s*$/m.test(body)) return true
  const listMatch = body.match(/^    needs:\s*\[([^\]]+)\]/m)
  if (!listMatch) return false
  return listMatch[1]
    .split(',')
    .map((item) => item.trim())
    .includes('runner_names')
}

export function splitJobs(source) {
  const lines = source.split(/\r?\n/)
  const jobsIndex = lines.findIndex((line) => line === 'jobs:')
  if (jobsIndex === -1) return []

  const jobs = []
  let current = null
  for (let i = jobsIndex + 1; i < lines.length; i++) {
    const line = lines[i]
    const jobMatch = line.match(/^  ([A-Za-z0-9_-]+):\s*$/)
    if (jobMatch) {
      if (current) jobs.push(current)
      current = { id: jobMatch[1], body: `${line}\n`, startLine: i }
      continue
    }
    if (current) current.body += `${line}\n`
  }
  if (current) jobs.push(current)
  return jobs
}

export function assertReusableMatchesCatalog(runners, reusableSource) {
  const expected = renderReusableWorkflow(runners)
  if (normalizeNewlines(reusableSource) !== normalizeNewlines(expected)) {
    throw new Error(
      `${REUSABLE_WORKFLOW} is out of date. Run: node .github/scripts/sync-runner-names.mjs`,
    )
  }
}

export function findMissingActionlintLabels(runners, actionlintSource) {
  const listed = new Set()
  const block = actionlintSource.split('labels:')[1] || ''
  for (const line of block.split(/\r?\n/)) {
    const match = line.match(/^\s+-\s+(\S+)\s*$/)
    if (match) listed.add(match[1])
  }
  return runners
    .map((entry) => entry.label)
    .filter((label) => label.startsWith('qvac-') && !listed.has(label))
}

function normalizeNewlines(text) {
  return text.replaceAll('\r\n', '\n')
}

export function readRepoFile(relativePath) {
  return readFileSync(join(repoRoot, relativePath), 'utf8')
}
