// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./generate-image-flux2.test.js')
  await import('./generate-image-sd3.test.js')
  await import('./generate-image-sdxl.test.js')
  await import('./generate-image.test.js')
  await import('./model-loading.test.js')

  test.resume()
}
