#!/usr/bin/env python3
"""Regenerate the Python client's typed surface (pydantic models + method
stubs) from the SDK contract (../sdk/contract/{schema,manifest}.json).

Usage:
  python3 scripts/generate.py            # write the generated files
  python3 scripts/generate.py --check    # exit 1 if committed output is stale
"""

from __future__ import annotations

import importlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_DIR = PACKAGE_ROOT.parent / "sdk" / "contract"
SCHEMA_PATH = CONTRACT_DIR / "schema.json"
MANIFEST_PATH = CONTRACT_DIR / "manifest.json"
MODELS_REGISTRY_JSON_PATH = CONTRACT_DIR / "models.json"
SRC_DIR = PACKAGE_ROOT / "src"
GENERATED_DIR = SRC_DIR / "qvac" / "_generated"
MODELS_DIR = GENERATED_DIR / "models"
INDEX_PATH = GENERATED_DIR / "__init__.py"
METHODS_PATH = GENERATED_DIR / "methods.py"
GENERATED_BASE_PATH = SRC_DIR / "qvac" / "_generated_base.py"
MODELS_REGISTRY_PATH = GENERATED_DIR / "models_registry.py"

CALL_SHAPE_ANNOTATION = {
    "request-reply": "reply",
    "server-stream": "stream",
    "duplex": "duplex",
}


def pascal_case(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in re.split(r"[:\-_]", name) if part
    )


def snake_case(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def load_manifest_methods() -> list[dict]:
    return json.loads(MANIFEST_PATH.read_text())["methods"]


def load_models_registry() -> dict[str, dict]:
    return json.loads(MODELS_REGISTRY_JSON_PATH.read_text())


def load_constant_titles() -> list[str]:
    """Titles of every public-constant $def schema.json carries alongside
    the request/response defs (`constants.ModelType`, `constants.PluginId`,
    ...) -- see @/schemas/constants-registry.ts and .cursor/rules/sdk/
    public-constants-contract.mdc in packages/sdk. These are plain top-level
    enum classes, generated by the same datamodel-code-generator run as
    everything else; resolve_titles just needs to know their names to
    re-export them the same way it re-exports every Request/Response."""
    schema = json.loads(SCHEMA_PATH.read_text())
    return sorted(
        defn["title"]
        for name, defn in schema["$defs"].items()
        if name.startswith("constants.")
    )


# (python field name, JSON field name, python type) for one ModelConstant.
MODEL_CONSTANT_FIELDS = [
    ("name", "name", "str"),
    ("src", "src", "str"),
    ("registry_path", "registryPath", "str"),
    ("registry_source", "registrySource", "str"),
    ("blob_core_key", "blobCoreKey", "str"),
    ("blob_block_offset", "blobBlockOffset", "int"),
    ("blob_block_length", "blobBlockLength", "int"),
    ("blob_byte_offset", "blobByteOffset", "int"),
    ("model_id", "modelId", "str"),
    ("expected_size", "expectedSize", "int"),
    ("sha256_checksum", "sha256Checksum", "str"),
    ("addon", "addon", "str"),
    ("engine", "engine", "str"),
    ("quantization", "quantization", "str"),
    ("params", "params", "str"),
]


def render_models_registry_module(catalog: dict[str, dict]) -> str:
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""Named model constants mirroring @qvac/sdk\'s @/models/registry',
        "catalog (contract/models.json) -- pass one directly as `modelSrc`; its",
        "`.src` field is a `registry://` wire string the worker resolves without",
        "a network round-trip when the model is already cached locally.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class ModelConstant:",
    ]
    for py_field, _, py_type in MODEL_CONSTANT_FIELDS:
        lines.append(f"    {py_field}: {py_type}")

    names = sorted(catalog)
    for name in names:
        entry = catalog[name]
        lines.append("")
        lines.append(f"{name} = ModelConstant(")
        for py_field, json_field, _ in MODEL_CONSTANT_FIELDS:
            lines.append(f"    {py_field}={entry[json_field]!r},")
        lines.append(")")

    lines.append("")
    lines.append("__all__ = [")
    lines.append('    "ModelConstant",')
    for name in names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def progress_wire_type(method: dict) -> str | None:
    """The wire `type` a progress-capable method's progress events carry
    (e.g. `modelProgress`), taken from the manifest's `progress.responseSchema`
    ref (`schema.json#/$defs/modelProgress.response`). `None` for methods
    with no `progress` block."""
    progress = method.get("progress")
    if not progress:
        return None
    def_name = progress["responseSchema"].rsplit("/", 1)[-1]
    suffix = ".response"
    if not def_name.endswith(suffix):
        raise RuntimeError(f'Unexpected progress responseSchema ref "{def_name}"')
    return def_name[: -len(suffix)]


def progress_response_title(method: dict) -> str | None:
    wire_type = progress_wire_type(method)
    return f"{pascal_case(wire_type)}Response" if wire_type else None


def run_datamodel_codegen(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(SCHEMA_PATH),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_dir),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--use-title-as-name",
            "--snake-case-field",
            "--target-python-version",
            "3.10",
            "--disable-timestamp",
            "--disable-warnings",
            "--use-double-quotes",
            # Emits `Annotated[int, Field(ge=...)]` instead of calling
            # conint(...)/constr(...) directly in a type position -- the
            # latter is invalid as a static type annotation, which is
            # what datamodel-code-generator's own docs say this flag is
            # headed toward becoming the pydantic v2 default for anyway.
            "--use-annotated",
            # See qvac._generated_base's docstring: makes enum-typed
            # fields' schema-literal defaults validate_default instead
            # of staying a bare str.
            "--base-class",
            "qvac._generated_base.GeneratedBaseModel",
        ],
        check=True,
    )


def resolve_titles(
    models_dir: Path, manifest_methods: list[dict]
) -> dict[str, tuple[str | None, str]]:
    """Map every request/response title to where it actually lives in a
    freshly generated `models` package: either directly (title is itself a
    top-level name) or via a per-method wrapper module exposing a bare
    `Request`/`Response` — datamodel-code-generator gives some titled unions
    their own module (named after the wire method) whose own top-level name
    is generic, not the title; see contract/README.md and this package's
    README for why. Returns `{title: (submodule_or_None, attribute_name)}`.

    Imports `models_dir` through a throwaway package tree under a fresh
    temp directory — never touches the real `sys.path`/`sys.modules` state
    or the committed `src/qvac/_generated/models`, so a `--check` run can't
    leave a partially-swapped tree behind if it's interrupted.
    """
    with tempfile.TemporaryDirectory() as fake_src:
        fake_qvac = Path(fake_src) / "qvac"
        fake_qvac.mkdir()
        (fake_qvac / "__init__.py").write_text("")
        shutil.copy(GENERATED_BASE_PATH, fake_qvac / "_generated_base.py")
        fake_generated = fake_qvac / "_generated"
        fake_generated.mkdir()
        (fake_generated / "__init__.py").write_text("")
        shutil.copytree(models_dir, fake_generated / "models")

        sys.path.insert(0, fake_src)
        try:
            models_pkg = importlib.import_module("qvac._generated.models")
            resolved: dict[str, tuple[str | None, str]] = {}

            def resolve(title: str, method_name: str | None, attr: str | None) -> None:
                if title in resolved:
                    return
                if hasattr(models_pkg, title):
                    resolved[title] = (None, title)
                    return
                if method_name is not None and attr is not None:
                    try:
                        submodule = importlib.import_module(
                            f"qvac._generated.models.{method_name}"
                        )
                    except ImportError:
                        submodule = None
                    if submodule is not None and hasattr(submodule, attr):
                        resolved[title] = (method_name, attr)
                        return
                context = f' (method "{method_name}")' if method_name else ""
                raise RuntimeError(
                    f'Could not resolve generated class for "{title}"{context}. '
                    "datamodel-code-generator's module-splitting changed shape — "
                    "extend resolve_titles in scripts/generate.py."
                )

            for method in manifest_methods:
                name = method["name"]
                resolve(f"{pascal_case(name)}Request", name, "Request")
                resolve(f"{pascal_case(name)}Response", name, "Response")
                progress_title = progress_response_title(method)
                if progress_title:
                    # Progress response schemas are shared response-union
                    # members, not per-method wrapper types, so there's no
                    # per-method submodule fallback to try for them.
                    resolve(progress_title, None, None)
            for constant_title in load_constant_titles():
                # Public constants (ModelType, PluginId, ...) are always
                # plain top-level classes, never per-method wrapped.
                resolve(constant_title, None, None)
            return resolved
        finally:
            sys.path.remove(fake_src)
            for module_name in list(sys.modules):
                if module_name == "qvac" or module_name.startswith("qvac."):
                    del sys.modules[module_name]


def render_index(resolved: dict[str, tuple[str | None, str]]) -> str:
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""Flat, stable re-export of every request/response model and public',
        "constant enum (ModelType, PluginId, ...), regardless of which",
        "internal module datamodel-code-generator placed it in.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    by_module: dict[str | None, list[tuple[str, str]]] = {}
    for title, (module, attr) in resolved.items():
        by_module.setdefault(module, []).append((attr, title))

    if None in by_module:
        names = sorted(title for _, title in by_module[None])
        lines.append(f"from .models import {', '.join(names)}")
    for module in sorted(m for m in by_module if m is not None):
        for attr, title in sorted(by_module[module]):
            lines.append(f"from .models.{module} import {attr} as {title}")

    lines.append("")
    lines.append("__all__ = [")
    for title in sorted(resolved):
        lines.append(f'    "{title}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_methods_module(manifest_methods: list[dict]) -> str:
    func_names: list[str] = []
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""One typed async function per contract/manifest.json entry, grouped',
        "by call shape: request-reply returns the response directly,",
        "server-stream/duplex return an async iterator of response chunks.",
        "",
        "Asyncio-native, matching the JS SDK. Each function only builds the",
        "wire payload and validates the reply — it takes a `Transport` to",
        "actually speak the wire protocol, which this package does not",
        "implement (see qvac._transport.Transport).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import AsyncIterable, AsyncIterator",
        "",
        "from .._transport import Transport",
        "from . import (",
    ]
    all_titles = sorted(
        {
            f"{pascal_case(m['name'])}{attr}"
            for m in manifest_methods
            for attr in ("Request", "Response")
        }
        | {title for m in manifest_methods if (title := progress_response_title(m))}
    )
    for title in all_titles:
        lines.append(f"    {title},")
    lines.append(")")
    lines.append("")

    for method in manifest_methods:
        name = method["name"]
        shape = CALL_SHAPE_ANNOTATION[method["callShape"]]
        func_name = snake_case(name)
        func_names.append(func_name)
        request_title = f"{pascal_case(name)}Request"
        response_title = f"{pascal_case(name)}Response"
        lines.append("")
        dump = "params.model_dump(mode='json', by_alias=True, exclude_unset=True)"
        if shape == "reply":
            lines.append(
                f"async def {func_name}(transport: Transport, params: {request_title}) -> {response_title}:"
            )
            lines.append(f"    payload = {dump}")
            lines.append(
                f"    return {response_title}.model_validate(await transport.call(payload))"
            )
        elif shape == "stream":
            lines.append(
                f"async def {func_name}(transport: Transport, params: {request_title}) -> AsyncIterator[{response_title}]:"
            )
            lines.append(f"    payload = {dump}")
            lines.append("    async for chunk in transport.call_stream(payload):")
            lines.append(f"        yield {response_title}.model_validate(chunk)")
        else:
            lines.append(
                f"async def {func_name}(\n"
                f"    transport: Transport, params: {request_title}, up: AsyncIterable[bytes]\n"
                f") -> AsyncIterator[{response_title}]:"
            )
            lines.append(f"    payload = {dump}")
            lines.append("    async for chunk in transport.call_duplex(payload, up):")
            lines.append(f"        yield {response_title}.model_validate(chunk)")
        lines.append("")

        wire_type = progress_wire_type(method)
        if wire_type:
            if shape != "reply":
                raise RuntimeError(
                    f'Method "{name}" has a progress block but call shape "{shape}" — '
                    "extend render_methods_module in scripts/generate.py to handle it."
                )
            progress_title = progress_response_title(method)
            func_names.append(f"{func_name}_with_progress")
            lines.append("")
            lines.append(
                f"async def {func_name}_with_progress(\n"
                f"    transport: Transport, params: {request_title}\n"
                f") -> AsyncIterator[{progress_title} | {response_title}]:"
            )
            lines.append(
                "    # Progress events and the terminal reply both arrive through the"
            )
            lines.append(
                "    # same stream, distinguished only by each payload's own `type` —"
            )
            lines.append(
                "    # call_stream already falls back cleanly to a single terminal"
            )
            lines.append(
                "    # chunk if the server ends up replying unary instead (e.g. an"
            )
            lines.append(
                "    # operation that doesn't support progress for this method)."
            )
            lines.append(f"    payload = {dump}")
            lines.append("    payload['withProgress'] = True")
            lines.append("    async for chunk in transport.call_stream(payload):")
            lines.append(f"        if chunk.get('type') == {wire_type!r}:")
            lines.append(f"            yield {progress_title}.model_validate(chunk)")
            lines.append("        else:")
            lines.append(f"            yield {response_title}.model_validate(chunk)")
            lines.append("")

    lines.append("")
    lines.append("__all__ = [")
    for func_name in sorted(func_names):
        lines.append(f'    "{func_name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def format_with_black(paths: list[Path]) -> None:
    subprocess.run(
        [sys.executable, "-m", "black", "--quiet", *[str(p) for p in paths]],
        check=True,
    )


def sort_imports_with_ruff(path: Path) -> None:
    # datamodel-code-generator appends the --base-class import as a plain
    # trailing line rather than running it through isort, so the header
    # block it emits isn't reliably sorted -- fix up just the "I" (import
    # sort) rules here rather than adding a whole extra lint pass.
    subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--select",
            "I",
            "--quiet",
            str(path),
        ],
        check=True,
    )


def build(output_root: Path) -> None:
    """Renders a complete `_generated/` tree (models/, __init__.py, methods.py,
    models_registry.py) into `output_root`. Never touches the real committed
    GENERATED_DIR."""
    models_dir = output_root / "models"
    run_datamodel_codegen(models_dir)
    sort_imports_with_ruff(models_dir)
    manifest_methods = load_manifest_methods()
    resolved = resolve_titles(models_dir, manifest_methods)

    index_path = output_root / "__init__.py"
    methods_path = output_root / "methods.py"
    models_registry_path = output_root / "models_registry.py"
    index_path.write_text(render_index(resolved))
    methods_path.write_text(render_methods_module(manifest_methods))
    models_registry_path.write_text(
        render_models_registry_module(load_models_registry())
    )
    format_with_black([index_path, methods_path, models_registry_path])


def compare_dirs(fresh: Path, committed: Path) -> bool:
    """Prints every difference between `fresh` and `committed`; returns
    whether they match exactly (recursively)."""
    if not committed.exists():
        print(f"{committed.relative_to(PACKAGE_ROOT)} is missing")
        return False
    import filecmp

    dcmp = filecmp.dircmp(fresh, committed)
    ok = not dcmp.left_only and not dcmp.right_only and not dcmp.diff_files
    for name in dcmp.left_only:
        print(f"missing: {(committed / name).relative_to(PACKAGE_ROOT)}")
    for name in dcmp.right_only:
        print(
            f"unexpected (stale, should be removed): {(committed / name).relative_to(PACKAGE_ROOT)}"
        )
    for name in dcmp.diff_files:
        print(f"out of date: {(committed / name).relative_to(PACKAGE_ROOT)}")
    for name in dcmp.common_dirs:
        ok = compare_dirs(fresh / name, committed / name) and ok
    return ok


def main() -> int:
    check_only = "--check" in sys.argv

    with tempfile.TemporaryDirectory() as tmp:
        output_root = Path(tmp) / "_generated"
        build(output_root)

        if check_only:
            if compare_dirs(output_root, GENERATED_DIR):
                return 0
            print(
                "Generated Python client is stale. Run 'python3 scripts/generate.py' and commit the result."
            )
            return 1

        if GENERATED_DIR.exists():
            shutil.rmtree(GENERATED_DIR)
        shutil.copytree(output_root, GENERATED_DIR)
        print(f"wrote {GENERATED_DIR.relative_to(PACKAGE_ROOT)}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
