#!/usr/bin/env python3
"""Regenerate the Python client's typed surface (pydantic models + method
stubs) from the SDK contract (../sdk/contract/{schema,manifest}.json).

Usage:
  python3 scripts/generate.py            # write the generated files
  python3 scripts/generate.py --check    # exit 1 if committed output is stale
"""

from __future__ import annotations

import importlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_DIR = PACKAGE_ROOT.parent / "sdk" / "contract"
SCHEMA_PATH = CONTRACT_DIR / "schema.json"
MANIFEST_PATH = CONTRACT_DIR / "manifest.json"
MODELS_REGISTRY_JSON_PATH = CONTRACT_DIR / "models.json"
MODEL_TYPE_MAPS_JSON_PATH = CONTRACT_DIR / "model-type-maps.json"
ERROR_CODES_JSON_PATH = CONTRACT_DIR / "error-codes.json"
SDK_PACKAGE_JSON_PATH = CONTRACT_DIR.parent / "package.json"
SRC_DIR = PACKAGE_ROOT / "src"
PACKAGE_DIR = SRC_DIR / "tetherto" / "qvac_sdk"
GENERATED_DIR = PACKAGE_DIR / "_generated"
MODELS_DIR = GENERATED_DIR / "models"
INDEX_PATH = GENERATED_DIR / "__init__.py"
METHODS_PATH = GENERATED_DIR / "methods.py"
GENERATED_BASE_PATH = PACKAGE_DIR / "_generated_base.py"
MODELS_REGISTRY_PATH = GENERATED_DIR / "models_registry.py"

CALL_SHAPE_ANNOTATION = {
    "request-reply": "reply",
    "server-stream": "stream",
    "duplex": "duplex",
}


def pascal_case(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in re.split(r"[:\-_]", name) if part
    )


def snake_case(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def load_manifest_methods() -> list[dict]:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))["methods"]


def load_models_registry() -> dict[str, dict]:
    return json.loads(MODELS_REGISTRY_JSON_PATH.read_text(encoding="utf-8"))


def load_model_type_maps() -> dict[str, dict[str, str]]:
    return json.loads(MODEL_TYPE_MAPS_JSON_PATH.read_text(encoding="utf-8"))


def load_error_codes() -> dict[str, dict[str, int]]:
    return json.loads(ERROR_CODES_JSON_PATH.read_text(encoding="utf-8"))


def load_sdk_version() -> str:
    return json.loads(SDK_PACKAGE_JSON_PATH.read_text(encoding="utf-8"))["version"]


def load_constant_titles() -> list[str]:
    """Titles of every public-constant $def schema.json carries alongside
    the request/response defs (`constants.ModelType`, `constants.PluginId`,
    ...) -- see @/schemas/constants-registry.ts and .cursor/rules/sdk/
    public-constants-contract.mdc in packages/sdk. These are plain top-level
    enum classes, generated by the same datamodel-code-generator run as
    everything else; resolve_titles just needs to know their names to
    re-export them the same way it re-exports every Request/Response."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return sorted(
        defn["title"]
        for name, defn in schema["$defs"].items()
        if name.startswith("constants.")
    )


# (python field name, JSON field name, python type) for one ModelConstant.
MODEL_CONSTANT_FIELDS = [
    ("name", "name", "str"),
    ("src", "src", "str"),
    ("registry_path", "registryPath", "str"),
    ("registry_source", "registrySource", "str"),
    ("blob_core_key", "blobCoreKey", "str"),
    ("blob_block_offset", "blobBlockOffset", "int"),
    ("blob_block_length", "blobBlockLength", "int"),
    ("blob_byte_offset", "blobByteOffset", "int"),
    ("model_id", "modelId", "str"),
    ("expected_size", "expectedSize", "int"),
    ("sha256_checksum", "sha256Checksum", "str"),
    ("addon", "addon", "str"),
    ("engine", "engine", "str"),
    ("quantization", "quantization", "str"),
    ("params", "params", "str"),
]


def render_models_registry_module(catalog: dict[str, dict]) -> str:
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""Named model constants mirroring @qvac/sdk\'s @/models/registry',
        "catalog (contract/models.json) -- pass one directly as `modelSrc`; its",
        "`.src` field is a `registry://` wire string the worker resolves without",
        "a network round-trip when the model is already cached locally.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class ModelConstant:",
    ]
    for py_field, _, py_type in MODEL_CONSTANT_FIELDS:
        lines.append(f"    {py_field}: {py_type}")

    names = sorted(catalog)
    for name in names:
        entry = catalog[name]
        lines.append("")
        lines.append(f"{name} = ModelConstant(")
        for py_field, json_field, _ in MODEL_CONSTANT_FIELDS:
            lines.append(f"    {py_field}={entry[json_field]!r},")
        lines.append(")")

    lines.append("")
    lines.append("__all__ = [")
    lines.append('    "ModelConstant",')
    for name in names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_model_type_maps_module(maps: dict[str, dict[str, str]]) -> str:
    """Emit the model-type resolution maps (contract/model-type-maps.json) as
    plain dict literals. `tetherto.qvac_sdk.model_types`'s inference reads these instead of
    hand-copying them, so an alias/engine edited on the SDK side surfaces as a
    `generate.py --check` failure rather than silently drifting."""
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""Model-type resolution maps mirroring @qvac/sdk\'s',
        "schemas/model-types.ts (ModelTypeAliases) and schemas/engine-addon-map.ts",
        "(ENGINE_TO_ADDON, LEGACY_ENGINE_TO_CANONICAL), exported via",
        "contract/model-type-maps.json.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    blocks = [
        ("ALIAS_TO_CANONICAL", "aliasToCanonical"),
        ("ENGINE_TO_ADDON", "engineToAddon"),
        ("LEGACY_ENGINE_TO_CANONICAL", "legacyEngineToCanonical"),
    ]
    for py_name, json_key in blocks:
        entries = maps[json_key]
        lines.append("")
        lines.append(f"{py_name}: dict[str, str] = {{")
        for key in sorted(entries):
            lines.append(f"    {key!r}: {entries[key]!r},")
        lines.append("}")

    lines.append("")
    lines.append("__all__ = [")
    for py_name, _ in blocks:
        lines.append(f'    "{py_name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_error_codes_module(codes: dict[str, dict[str, int]]) -> str:
    """Emit the SDK error-code registries (contract/error-codes.json) as plain
    dict literals. `tetherto.qvac_sdk.errors` reads these instead of hand-copying the
    numbers, so a code added or renamed on the SDK side surfaces as a
    `generate.py --check` failure."""
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""SDK error-code registries (name -> numeric code) mirroring',
        "@qvac/sdk's schemas/sdk-errors-{server,client,registry}.ts, exported via",
        "contract/error-codes.json.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    blocks = [
        ("SERVER_ERROR_CODES", "server"),
        ("CLIENT_ERROR_CODES", "client"),
        ("REGISTRY_ERROR_CODES", "registry"),
    ]
    for py_name, json_key in blocks:
        entries = codes[json_key]
        lines.append("")
        lines.append(f"{py_name}: dict[str, int] = {{")
        for key in sorted(entries):
            lines.append(f"    {key!r}: {entries[key]!r},")
        lines.append("}")

    lines.append("")
    lines.append("__all__ = [")
    for py_name, _ in blocks:
        lines.append(f'    "{py_name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_sdk_version_module(version: str) -> str:
    """Emit the `@qvac/sdk` version this client's contract was generated from.
    The worker the client talks to must be this version (the generated wire
    shapes match it), so `Client` and `python -m tetherto.qvac_sdk install-worker` pin to it.
    Regenerated from packages/sdk/package.json, so a version bump surfaces via
    generate.py --check."""
    return (
        "# Generated by scripts/generate.py. Do not edit by hand.\n"
        '"""The `@qvac/sdk` version this generated client matches; the worker it\n'
        "connects to must be this version. Sourced from packages/sdk/package.json.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f'SDK_VERSION = "{version}"\n\n'
        '__all__ = ["SDK_VERSION"]\n'
    )


def progress_wire_type(method: dict) -> str | None:
    """The wire `type` a progress-capable method's progress events carry
    (e.g. `modelProgress`), taken from the manifest's `progress.responseSchema`
    ref (`schema.json#/$defs/modelProgress.response`). `None` for methods
    with no `progress` block."""
    progress = method.get("progress")
    if not progress:
        return None
    def_name = progress["responseSchema"].rsplit("/", 1)[-1]
    suffix = ".response"
    if not def_name.endswith(suffix):
        raise RuntimeError(f'Unexpected progress responseSchema ref "{def_name}"')
    return def_name[: -len(suffix)]


def progress_response_title(method: dict) -> str | None:
    wire_type = progress_wire_type(method)
    return f"{pascal_case(wire_type)}Response" if wire_type else None


def run_datamodel_codegen(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(SCHEMA_PATH),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_dir),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--use-title-as-name",
            "--snake-case-field",
            "--target-python-version",
            "3.10",
            "--disable-timestamp",
            "--disable-warnings",
            "--use-double-quotes",
            # Emits `Annotated[int, Field(ge=...)]` instead of calling
            # conint(...)/constr(...) directly in a type position -- the
            # latter is invalid as a static type annotation, which is
            # what datamodel-code-generator's own docs say this flag is
            # headed toward becoming the pydantic v2 default for anyway.
            "--use-annotated",
            # A single-value Literal is the wire discriminator (`type:
            # Literal["embed"]`); defaulting it means callers never pass the
            # redundant `type="embed"`, so a generated request is ergonomic
            # enough to stand in for a hand-written wrapper. validate_default
            # (see below) keeps the defaulted value validated.
            "--use-one-literal-as-default",
            # See tetherto.qvac_sdk._generated_base's docstring: makes enum-typed
            # fields' schema-literal defaults validate_default instead
            # of staying a bare str.
            "--base-class",
            "tetherto.qvac_sdk._generated_base.GeneratedBaseModel",
        ],
        check=True,
    )


def resolve_titles(
    models_dir: Path, manifest_methods: list[dict]
) -> dict[str, tuple[str | None, str]]:
    """Map every request/response title to where it actually lives in a
    freshly generated `models` package: either directly (title is itself a
    top-level name) or via a per-method wrapper module exposing a bare
    `Request`/`Response` — datamodel-code-generator gives some titled unions
    their own module (named after the wire method) whose own top-level name
    is generic, not the title; see contract/README.md and this package's
    README for why. Returns `{title: (submodule_or_None, attribute_name)}`.

    Imports `models_dir` through a throwaway package tree under a fresh
    temp directory — never touches the real `sys.path`/`sys.modules` state
    or the committed `src/tetherto/qvac_sdk/_generated/models`, so a `--check`
    run can't leave a partially-swapped tree behind if it's interrupted.
    """
    pkg_prefix = "tetherto.qvac_sdk"
    with tempfile.TemporaryDirectory() as fake_src:
        # Mirror the real layout: `tetherto` is a PEP 420 namespace (no
        # __init__), `qvac_sdk` a regular package, so the generated code's
        # absolute `from tetherto.qvac_sdk._generated_base import ...` resolves.
        fake_pkg = Path(fake_src) / "tetherto" / "qvac_sdk"
        fake_pkg.mkdir(parents=True)
        (fake_pkg / "__init__.py").write_text("", encoding="utf-8")
        shutil.copy(GENERATED_BASE_PATH, fake_pkg / "_generated_base.py")
        fake_generated = fake_pkg / "_generated"
        fake_generated.mkdir()
        (fake_generated / "__init__.py").write_text("", encoding="utf-8")
        shutil.copytree(models_dir, fake_generated / "models")

        # Snapshot any already-imported real tetherto.* modules so they can be
        # restored afterwards, and drop them first so the fake tree resolves
        # instead of the real namespace. Deleting without restoring would make a
        # later in-process `from .x import y` re-import a FRESH copy of a package
        # module -- module-level state (e.g. the logging-stream registry) would
        # silently fork from the copies callers already hold. Only bites
        # same-process users (pytest); a CLI run exits.
        def _is_pkg_module(name: str) -> bool:
            return name == "tetherto" or name.startswith("tetherto.")

        saved_pkg_modules = {
            name: module for name, module in sys.modules.items() if _is_pkg_module(name)
        }
        for name in list(sys.modules):
            if _is_pkg_module(name):
                del sys.modules[name]
        sys.path.insert(0, fake_src)
        try:
            models_pkg = importlib.import_module(f"{pkg_prefix}._generated.models")
            resolved: dict[str, tuple[str | None, str]] = {}

            def resolve(title: str, method_name: str | None, attr: str | None) -> None:
                if title in resolved:
                    return
                if hasattr(models_pkg, title):
                    resolved[title] = (None, title)
                    return
                if method_name is not None and attr is not None:
                    try:
                        submodule = importlib.import_module(
                            f"{pkg_prefix}._generated.models.{method_name}"
                        )
                    except ImportError:
                        submodule = None
                    if submodule is not None and hasattr(submodule, attr):
                        resolved[title] = (method_name, attr)
                        return
                context = f' (method "{method_name}")' if method_name else ""
                raise RuntimeError(
                    f'Could not resolve generated class for "{title}"{context}. '
                    "datamodel-code-generator's module-splitting changed shape — "
                    "extend resolve_titles in scripts/generate.py."
                )

            for method in manifest_methods:
                name = method["name"]
                resolve(f"{pascal_case(name)}Request", name, "Request")
                resolve(f"{pascal_case(name)}Response", name, "Response")
                progress_title = progress_response_title(method)
                if progress_title:
                    # Progress response schemas are shared response-union
                    # members, not per-method wrapper types, so there's no
                    # per-method submodule fallback to try for them.
                    resolve(progress_title, None, None)
            for constant_title in load_constant_titles():
                # Public constants (ModelType, PluginId, ...) are always
                # plain top-level classes, never per-method wrapped.
                resolve(constant_title, None, None)
            return resolved
        finally:
            sys.path.remove(fake_src)
            for module_name in list(sys.modules):
                if _is_pkg_module(module_name):
                    del sys.modules[module_name]
            sys.modules.update(saved_pkg_modules)


def render_index(resolved: dict[str, tuple[str | None, str]]) -> str:
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""Flat, stable re-export of every request/response model and public',
        "constant enum (ModelType, PluginId, ...), regardless of which",
        "internal module datamodel-code-generator placed it in.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    by_module: dict[str | None, list[tuple[str, str]]] = {}
    for title, (module, attr) in resolved.items():
        by_module.setdefault(module, []).append((attr, title))

    if None in by_module:
        names = sorted(title for _, title in by_module[None])
        lines.append(f"from .models import {', '.join(names)}")
    for module in sorted(m for m in by_module if m is not None):
        for attr, title in sorted(by_module[module]):
            lines.append(f"from .models.{module} import {attr} as {title}")

    lines.append("")
    lines.append("__all__ = [")
    for title in sorted(resolved):
        lines.append(f'    "{title}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_methods_module(manifest_methods: list[dict]) -> str:
    func_names: list[str] = []
    lines = [
        "# Generated by scripts/generate.py. Do not edit by hand.",
        '"""One typed async function per contract/manifest.json entry, grouped',
        "by call shape: request-reply returns the response directly,",
        "server-stream/duplex return an async iterator of response chunks.",
        "",
        "Asyncio-native, matching the JS SDK. Each function only builds the",
        "wire payload and validates the reply — it takes a `Transport` to",
        "actually speak the wire protocol, which this package does not",
        "implement (see tetherto.qvac_sdk._transport.Transport).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import AsyncIterable, AsyncIterator",
        "",
        "from .._transport import Transport",
        "from . import (",
    ]
    all_titles = sorted(
        {
            f"{pascal_case(m['name'])}{attr}"
            for m in manifest_methods
            for attr in ("Request", "Response")
        }
        | {title for m in manifest_methods if (title := progress_response_title(m))}
    )
    for title in all_titles:
        lines.append(f"    {title},")
    lines.append(")")
    lines.append("")

    for method in manifest_methods:
        name = method["name"]
        shape = CALL_SHAPE_ANNOTATION[method["callShape"]]
        func_name = snake_case(name)
        func_names.append(func_name)
        request_title = f"{pascal_case(name)}Request"
        response_title = f"{pascal_case(name)}Response"
        lines.append("")
        dump = "params.model_dump(mode='json', by_alias=True, exclude_unset=True)"
        if shape == "reply":
            lines.append(
                f"async def {func_name}(transport: Transport, params: {request_title}) -> {response_title}:"
            )
            lines.append(f"    payload = {dump}")
            lines.append(
                f"    return {response_title}.model_validate(await transport.call(payload))"
            )
        elif shape == "stream":
            lines.append(
                f"async def {func_name}(transport: Transport, params: {request_title}) -> AsyncIterator[{response_title}]:"
            )
            lines.append(f"    payload = {dump}")
            lines.append("    async for chunk in transport.call_stream(payload):")
            lines.append(f"        yield {response_title}.model_validate(chunk)")
        else:
            lines.append(
                f"async def {func_name}(\n"
                f"    transport: Transport, params: {request_title}, up: AsyncIterable[bytes]\n"
                f") -> AsyncIterator[{response_title}]:"
            )
            lines.append(f"    payload = {dump}")
            lines.append("    async for chunk in transport.call_duplex(payload, up):")
            lines.append(f"        yield {response_title}.model_validate(chunk)")
        lines.append("")

        wire_type = progress_wire_type(method)
        if wire_type:
            if shape != "reply":
                raise RuntimeError(
                    f'Method "{name}" has a progress block but call shape "{shape}" — '
                    "extend render_methods_module in scripts/generate.py to handle it."
                )
            progress_title = progress_response_title(method)
            func_names.append(f"{func_name}_with_progress")
            lines.append("")
            lines.append(
                f"async def {func_name}_with_progress(\n"
                f"    transport: Transport, params: {request_title}\n"
                f") -> AsyncIterator[{progress_title} | {response_title}]:"
            )
            lines.append(
                "    # Progress events and the terminal reply both arrive through the"
            )
            lines.append(
                "    # same stream, distinguished only by each payload's own `type` —"
            )
            lines.append(
                "    # call_stream already falls back cleanly to a single terminal"
            )
            lines.append(
                "    # chunk if the server ends up replying unary instead (e.g. an"
            )
            lines.append(
                "    # operation that doesn't support progress for this method)."
            )
            lines.append(f"    payload = {dump}")
            lines.append("    payload['withProgress'] = True")
            lines.append("    async for chunk in transport.call_stream(payload):")
            lines.append(f"        if chunk.get('type') == {wire_type!r}:")
            lines.append(f"            yield {progress_title}.model_validate(chunk)")
            lines.append("        else:")
            lines.append(f"            yield {response_title}.model_validate(chunk)")
            lines.append("")

    lines.append("")
    lines.append("__all__ = [")
    for func_name in sorted(func_names):
        lines.append(f'    "{func_name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def format_with_black(paths: list[Path]) -> None:
    subprocess.run(
        [sys.executable, "-m", "black", "--quiet", *[str(p) for p in paths]],
        check=True,
    )


def sort_imports_with_ruff(path: Path) -> None:
    # datamodel-code-generator appends the --base-class import as a plain
    # trailing line rather than running it through isort, so the header
    # block it emits isn't reliably sorted -- fix up just the "I" (import
    # sort) rules here rather than adding a whole extra lint pass.
    #
    # --config is explicit because the build renders into a temp dir; without
    # it ruff can't discover the package pyproject up the path, falls back to
    # defaults, and classifies the first-party `tetherto` import as third-party --
    # so the temp build and the committed (config-aware) output disagree by a
    # blank line and `--check` flakes.
    subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "--fix",
            "--select",
            "I",
            "--config",
            str(PACKAGE_ROOT / "pyproject.toml"),
            "--quiet",
            str(path),
        ],
        check=True,
    )


def build(output_root: Path) -> None:
    """Renders a complete `_generated/` tree (models/, __init__.py, methods.py,
    models_registry.py) into `output_root`. Never touches the real committed
    GENERATED_DIR."""
    models_dir = output_root / "models"
    run_datamodel_codegen(models_dir)
    sort_imports_with_ruff(models_dir)
    manifest_methods = load_manifest_methods()
    resolved = resolve_titles(models_dir, manifest_methods)

    index_path = output_root / "__init__.py"
    methods_path = output_root / "methods.py"
    models_registry_path = output_root / "models_registry.py"
    model_type_maps_path = output_root / "model_type_maps.py"
    error_codes_path = output_root / "error_codes.py"
    sdk_version_path = output_root / "sdk_version.py"
    index_path.write_text(render_index(resolved), encoding="utf-8")
    methods_path.write_text(render_methods_module(manifest_methods), encoding="utf-8")
    models_registry_path.write_text(
        render_models_registry_module(load_models_registry()), encoding="utf-8"
    )
    model_type_maps_path.write_text(
        render_model_type_maps_module(load_model_type_maps()), encoding="utf-8"
    )
    error_codes_path.write_text(
        render_error_codes_module(load_error_codes()), encoding="utf-8"
    )
    sdk_version_path.write_text(
        render_sdk_version_module(load_sdk_version()), encoding="utf-8"
    )
    format_with_black(
        [
            index_path,
            methods_path,
            models_registry_path,
            model_type_maps_path,
            error_codes_path,
            sdk_version_path,
        ]
    )


def compare_dirs(fresh: Path, committed: Path) -> bool:
    """Prints every difference between `fresh` and `committed`; returns
    whether they match exactly (recursively)."""
    if not committed.exists():
        print(f"{committed.relative_to(PACKAGE_ROOT)} is missing")
        return False
    import filecmp

    dcmp = filecmp.dircmp(fresh, committed)
    ok = not dcmp.left_only and not dcmp.right_only
    for name in dcmp.left_only:
        print(f"missing: {(committed / name).relative_to(PACKAGE_ROOT)}")
    for name in dcmp.right_only:
        print(
            f"unexpected (stale, should be removed): {(committed / name).relative_to(PACKAGE_ROOT)}"
        )
    # Compare common files by newline-normalized content, not filecmp's stat
    # signature: on Windows a fresh build writes the platform-default CRLF while
    # the committed tree is LF, so a byte/size comparison would flag every file
    # as differing on a pure line-ending artifact. The generator's guarantee is
    # about logical content, so any real drift still fails.
    for name in dcmp.common_files:
        fresh_text = (fresh / name).read_text(encoding="utf-8").replace("\r\n", "\n")
        committed_text = (
            (committed / name).read_text(encoding="utf-8").replace("\r\n", "\n")
        )
        if fresh_text != committed_text:
            print(f"out of date: {(committed / name).relative_to(PACKAGE_ROOT)}")
            ok = False
    for name in dcmp.common_dirs:
        ok = compare_dirs(fresh / name, committed / name) and ok
    return ok


def render_plugin_module(contract: dict) -> str:
    """Typed client module for one custom plugin's handlers, generated
    through the same pipeline as the built-in surface: pydantic models via
    datamodel-code-generator, plus one async function per handler over
    invoke_plugin / invoke_plugin_stream. The plugin contract JSON comes
    from the SDK's `scripts/export-plugin-contract.ts`."""
    model_type = contract["modelType"]
    defs: dict[str, dict] = {}
    for handler in contract["handlers"]:
        base = pascal_case(handler["name"])
        defs[f"{base}Request"] = {
            "title": f"{base}Request",
            **handler["requestSchema"],
        }
        defs[f"{base}Response"] = {
            "title": f"{base}Response",
            **handler["responseSchema"],
        }

    schema_doc = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$defs": defs,
    }
    with tempfile.TemporaryDirectory() as tmp:
        schema_path = Path(tmp) / "plugin-schema.json"
        schema_path.write_text(json.dumps(schema_doc), encoding="utf-8")
        models_path = Path(tmp) / "models.py"
        run_datamodel_codegen_single(schema_path, models_path)
        models_source = models_path.read_text(encoding="utf-8")

    lines = [
        "# Generated by scripts/generate.py --plugin. Do not edit by hand.",
        f'"""Typed client for the custom {model_type!r} plugin\'s handlers,',
        "over tetherto.qvac_sdk.invoke_plugin / invoke_plugin_stream.",
        '"""',
        "",
        models_source,
        "",
        "from collections.abc import AsyncIterator  # noqa: E402",
        "",
        "from tetherto.qvac_sdk import invoke_plugin, invoke_plugin_stream  # noqa: E402",
        "from tetherto.qvac_sdk._transport import Transport  # noqa: E402",
        "",
        f'MODEL_TYPE = "{model_type}"',
        "",
    ]
    func_names: list[str] = []
    for handler in contract["handlers"]:
        base = pascal_case(handler["name"])
        func = snake_case(handler["name"])
        func_names.append(func)
        dump = 'params.model_dump(mode="json", by_alias=True, exclude_unset=True)'
        if handler["streaming"]:
            lines += [
                f"async def {func}(",
                f"    transport: Transport, model_id: str, params: {base}Request",
                f") -> AsyncIterator[{base}Response]:",
                f'    async for chunk in invoke_plugin_stream(transport, model_id, "{handler["name"]}", {dump}):',
                f"        yield {base}Response.model_validate(chunk)",
                "",
            ]
        else:
            lines += [
                f"async def {func}(",
                f"    transport: Transport, model_id: str, params: {base}Request",
                f") -> {base}Response:",
                f'    result = await invoke_plugin(transport, model_id, "{handler["name"]}", {dump})',
                f"    return {base}Response.model_validate(result)",
                "",
            ]
    lines.append("__all__ = [")
    for func in sorted(func_names):
        lines.append(f'    "{func}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def run_datamodel_codegen_single(schema_path: Path, output_path: Path) -> None:
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--use-title-as-name",
            "--snake-case-field",
            "--target-python-version",
            "3.10",
            "--disable-timestamp",
            "--disable-warnings",
            "--use-double-quotes",
            "--use-annotated",
            "--base-class",
            "tetherto.qvac_sdk._generated_base.GeneratedBaseModel",
        ],
        check=True,
    )


def generate_plugins(args: list[str]) -> int:
    """`generate.py --plugin a.json [b.json ...] [--plugins-out DIR]`:
    write one typed module per plugin contract into DIR (default
    src/tetherto/qvac_sdk/plugins/)."""
    out_dir = PACKAGE_DIR / "plugins"
    if "--plugins-out" in args:
        out_dir = Path(args[args.index("--plugins-out") + 1])
    contracts = [
        Path(value) for flag, value in zip(args, args[1:]) if flag == "--plugin"
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    init_path = out_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("", encoding="utf-8")
    for contract_path in contracts:
        contract = json.loads(contract_path.read_text(encoding="utf-8"))
        module_path = out_dir / f"{snake_case(contract['modelType'])}.py"
        module_path.write_text(render_plugin_module(contract), encoding="utf-8")
        format_with_black([module_path])
        sort_imports_with_ruff(module_path)
        print(f"wrote {module_path}")
    return 0


def main() -> int:
    if "--plugin" in sys.argv:
        return generate_plugins(sys.argv[1:])
    check_only = "--check" in sys.argv

    with tempfile.TemporaryDirectory() as tmp:
        output_root = Path(tmp) / "_generated"
        build(output_root)

        if check_only:
            if compare_dirs(output_root, GENERATED_DIR):
                return 0
            print(
                "Generated Python client is stale. Run 'python3 scripts/generate.py' and commit the result."
            )
            return 1

        if GENERATED_DIR.exists():
            shutil.rmtree(GENERATED_DIR)
        shutil.copytree(output_root, GENERATED_DIR)
        print(f"wrote {GENERATED_DIR.relative_to(PACKAGE_ROOT)}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
