import { z } from "zod";
import {
  transcribeSegmentSchema,
  transcribeStatsSchema,
  type TranscribeSegment,
} from "./transcription";

// Neural-signal binary input. The BCI addon consumes a raw neural buffer
// (not audio): pass it inline as base64 or point at a local `.bin` file.
export const neuralInputSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("base64"),
    value: z.string(),
  }),
  z.object({
    type: z.literal("filePath"),
    value: z.string(),
  }),
]);

const bciTranscribeBaseSchema = z.object({
  modelId: z.string(),
  /**
   * When true, the response yields per-segment metadata objects
   * (`{ text, startMs, endMs, append, id }`) instead of joined text.
   */
  metadata: z.boolean().optional(),
});

export const bciTranscribeParamsSchema = bciTranscribeBaseSchema.extend({
  neuralData: neuralInputSchema,
});

export const bciTranscribeRequestSchema = bciTranscribeParamsSchema.extend({
  type: z.literal("bciTranscribe"),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      "Stable identifier for this in-flight BCI transcription, generated by the client at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional on the wire — the server falls back to a server-generated id when the field is missing.",
    ),
});

const bciTranscriptionResultBase = z.object({
  text: z.string().optional(),
  done: z.boolean().optional(),
  stats: transcribeStatsSchema.optional(),
  error: z.string().optional(),
  segment: transcribeSegmentSchema.optional(),
});

export const bciTranscribeResponseSchema = bciTranscriptionResultBase.extend({
  type: z.literal("bciTranscribe"),
});

/**
 * Per-call overrides for the BCI addon's sliding-window streaming
 * (`transcribeStream`). Each field maps 1:1 to the addon's `streamOpts`;
 * any field omitted falls back to the addon default.
 */
export const bciStreamOptsSchema = z.object({
  windowTimesteps: z
    .number()
    .int()
    .positive()
    .optional()
    .describe("Decode window size in timesteps (addon default: 1500)."),
  hopTimesteps: z
    .number()
    .int()
    .positive()
    .optional()
    .describe(
      "How far the window advances between decodes (addon default: 500). Must be < windowTimesteps.",
    ),
  emit: z
    .enum(["delta", "full"])
    .optional()
    .describe(
      "'delta' (default) emits only the newly-discovered tail per window; 'full' emits the full running transcript each update.",
    ),
});

export const bciTranscribeStreamRequestSchema = bciTranscribeBaseSchema.extend({
  type: z.literal("bciTranscribeStream"),
  streamOpts: bciStreamOptsSchema.optional(),
  requestId: z
    .string()
    .min(1)
    .optional()
    .describe(
      "Stable identifier for this in-flight duplex BCI transcription, generated by the client at call time. Surfaces on the registry so callers can target it with `cancel({ requestId })`. Optional on the wire — the server falls back to a server-generated id when the field is missing.",
    ),
});

export const bciTranscribeStreamResponseSchema =
  bciTranscriptionResultBase.extend({
    type: z.literal("bciTranscribeStream"),
  });

export type NeuralInput = z.infer<typeof neuralInputSchema>;
export type BciTranscribeParams = z.infer<typeof bciTranscribeParamsSchema>;
export type BciTranscribeRequest = z.infer<typeof bciTranscribeRequestSchema>;
export type BciTranscribeResponse = z.infer<typeof bciTranscribeResponseSchema>;
export type BciStreamOpts = z.infer<typeof bciStreamOptsSchema>;
export type BciTranscribeStreamRequest = z.infer<
  typeof bciTranscribeStreamRequestSchema
>;
export type BciTranscribeStreamResponse = z.infer<
  typeof bciTranscribeStreamResponseSchema
>;

export type BciTranscribeClientParams = {
  modelId: string;
  neuralData: string | Uint8Array;
  metadata?: boolean;
};

export type BciTranscribeStreamClientParams = {
  modelId: string;
  metadata?: boolean;
  windowTimesteps?: number;
  hopTimesteps?: number;
  emit?: "delta" | "full";
};

export interface BciTranscribeStreamSession {
  write(neuralChunk: Uint8Array): void;
  end(): void;
  destroy(): void;
  [Symbol.asyncIterator](): AsyncIterator<string>;
}

export interface BciTranscribeStreamMetadataSession {
  write(neuralChunk: Uint8Array): void;
  end(): void;
  destroy(): void;
  [Symbol.asyncIterator](): AsyncIterator<TranscribeSegment>;
}
