/**
 * Open Graph helpers for documentation pages — canonical URLs and version slug detection.
 * @see https://ogp.me/
 */

import {
  API_SECTION,
  RELEASE_NOTES_SECTION,
  type VersionedSection,
} from './versions';

export const DOCS_SITE_ORIGIN = 'https://docs.qvac.tether.io';

const VERSION_SLUG_RE = /^v\d+\.\d+\.\d+$/;

/**
 * Versioned sections whose **archived** (non-latest) snapshots are hidden
 * from indexing, sitemap, llms.txt, llms-full.txt, per-page `.md`, and
 * JSON-LD, AND whose HTML pages carry `<meta robots="noindex">` with a
 * `<link rel="canonical">` pointing to the section's latest URL.
 *
 * Per-section policy:
 *
 * - **API summary** (`API_SECTION`) — IS hidden. Each version of the API
 *   reference is mostly the same surface re-printed with marginal diffs
 *   (near-duplicate content). Letting Google index all of them dilutes
 *   ranking signals across the four pages instead of consolidating
 *   authority on `/reference/api`. AI ingestion of multiple snapshots also
 *   risks cross-version hallucination (an LLM mixing assignatures from
 *   v0.7.0 and v0.10.2). Better to fold the back-versions into the
 *   canonical "latest" page.
 *
 * - **Release notes** (`RELEASE_NOTES_SECTION`) — NOT hidden. Each archive
 *   is a uniquely-valuable historical document describing what changed in
 *   a specific release. There is no duplicate-content problem (every page
 *   has distinct text), and excluding them from search makes
 *   "what changed in v0.8.0?" undiscoverable. Each archived release-note
 *   page stays its own canonical and is indexed everywhere the latest
 *   release-note is (sitemap, `llms.txt`, per-page `.md`). The lone
 *   exception is `llms-full.txt`, which drops the whole release-notes
 *   section via `isReleaseNotesPage` to shrink the dump's token footprint
 *   (QVAC-21379) — a scope filter for that one artefact, not an indexing
 *   decision.
 */
const SECTIONS_HIDDEN_FROM_INDEXING: VersionedSection[] = [API_SECTION];

/**
 * Versioned sections whose latest exists at the bare basePath but whose
 * archives are not hidden. Used by `buildPageCanonicalUrl` to confirm that
 * a `vX.Y.Z` page is a legitimate, indexable archive vs. a typo that
 * happens to match the version regex.
 */
const SECTIONS_KEPT_INDEXED: VersionedSection[] = [RELEASE_NOTES_SECTION];

/**
 * Map of archived page URL → section it belongs to, restricted to sections
 * whose archives are hidden from indexing. The map (rather than a `Set`) lets
 * `buildPageCanonicalUrl` look up the section in O(1) so it can return the
 * URL of the section's latest as the canonical target.
 *
 * Built once at module load from `versions.ts` — auto-updated whenever the
 * version list is regenerated by `scripts/update-versions-list.ts`, so we
 * never have to hand-maintain a parallel list.
 *
 * URLs are normalized (no trailing slash, no `index` suffix) to match what
 * `source.getPages()` exposes via `page.url`.
 */
const HIDDEN_ARCHIVED_PAGE_TO_SECTION: ReadonlyMap<string, VersionedSection> =
  buildHiddenArchivedPageMap(SECTIONS_HIDDEN_FROM_INDEXING);

function buildHiddenArchivedPageMap(
  sections: VersionedSection[],
): Map<string, VersionedSection> {
  const map = new Map<string, VersionedSection>();
  for (const section of sections) {
    for (const version of section.versions) {
      if (version.isLatest) continue;
      map.set(`${section.basePath}/${version.value}`, section);
    }
  }
  return map;
}

/**
 * Minimal shape of a fumadocs page consumed by `isArchivedPage`. Decoupled
 * from `InferPageType<typeof source>` so this module stays importable from
 * tests, Node scripts, and the fumadocs route handlers without dragging the
 * full source typing.
 */
export interface ArchivePageRef {
  url: string;
  slugs: string[];
}

/**
 * True when the page is an archived snapshot in a section whose archives are
 * hidden from indexing (currently: API summary only — see
 * `SECTIONS_HIDDEN_FROM_INDEXING`). Consumed by:
 *
 * - `sitemap.ts` — to omit hidden archives from `sitemap.xml`.
 * - `llms.txt`, `llms-full.txt` — to omit them from the aggregate AI
 *   catalogs (training-corpus artefacts where excluding archives
 *   meaningfully reduces cross-version ingestion).
 * - `page.tsx` (via `isArchivedVersionSlug`) — to add `noindex` metadata.
 * - `docs-json-ld.ts` (via `isArchivedVersionSlug`) — to skip JSON-LD.
 *
 * NOT consumed by `llm-md-manifest.json`: per-page `.md` files are emitted
 * for every page regardless of archive status, because they are alternate
 * representations of already-public HTML pages and gating them only breaks
 * the "Copy as Markdown" action and the `Accept: text/markdown` content-
 * negotiation flow without adding SEO/AI protection. See the comment in
 * `src/app/llm-md-manifest.json/route.ts` for the full rationale.
 *
 * Returns `false` for archived snapshots of sections that we intentionally
 * keep indexed (e.g. release-notes back-versions): those pages are visible
 * to crawlers and listed in the sitemap and llms.txt. (They are still kept
 * out of the `llms-full.txt` bulk dump — but by the separate
 * `isReleaseNotesPage` filter, not by this function; see QVAC-21379.)
 *
 * Also returns `true` for legacy bundle-style URLs (`/vX.Y.Z/...` with the
 * version slug as the first segment), as a defensive fallback against any
 * stray page left over from the pre-section versioning model.
 */
export function isArchivedPage(page: ArchivePageRef): boolean {
  if (HIDDEN_ARCHIVED_PAGE_TO_SECTION.has(page.url)) return true;
  return isLegacyBundleSlug(page.slugs);
}

/**
 * True when the page belongs to the release-notes section — its latest
 * (`/reference/release-notes`) or any archived series
 * (`/reference/release-notes/vX.Y.x`).
 *
 * Used exclusively by `llms-full.txt` to keep release notes out of the
 * full-documentation dump (QVAC-21379): each release note is a historical
 * changelog whose bulk text bloats the agent's token budget and dilutes its
 * reasoning without adding context it needs for day-to-day SDK usage. Release
 * notes stay indexed and discoverable everywhere else (sitemap, `llms.txt`,
 * per-page `.md`); an agent that specifically needs "what changed in vX.Y?"
 * can still fetch the individual page on demand.
 *
 * Deliberately separate from `isArchivedPage`: this is a scope-reduction
 * filter for one artefact, not the "hidden near-duplicate archive" policy.
 */
export function isReleaseNotesPage(page: ArchivePageRef): boolean {
  const base = RELEASE_NOTES_SECTION.basePath;
  return page.url === base || page.url.startsWith(base + '/');
}

function isLegacyBundleSlug(slugs: string[] | undefined): boolean {
  if (!slugs?.length) return false;
  return VERSION_SLUG_RE.test(slugs[0]);
}

/**
 * Slug-only variant of `isArchivedPage` for the few call sites that have the
 * raw `params.slug` array but not a fumadocs `page` object (per-page
 * `generateMetadata` in `app/(docs)/[[...slug]]/page.tsx` and the JSON-LD
 * builder in `docs-json-ld.ts`).
 *
 * Reconstructs the canonical page URL (`'/' + slugs.join('/')`) so the
 * manifest-based check still applies, and falls back to the legacy
 * bundle-slug regex.
 */
export function isArchivedVersionSlug(slugs: string[] | undefined): boolean {
  if (!slugs?.length) return false;
  const url = '/' + slugs.join('/');
  if (HIDDEN_ARCHIVED_PAGE_TO_SECTION.has(url)) return true;
  return isLegacyBundleSlug(slugs);
}

/**
 * Bare self-URL for a docs page. Used internally by `buildPageCanonicalUrl`
 * and exported for non-canonical Open Graph use cases (e.g. share URLs that
 * always point at the exact page the user is on, regardless of whether it
 * is the SEO canonical).
 *
 * Always returns URLs **with a trailing slash** to match the site's
 * canonical form (Next.js is configured with `trailingSlash: true`, and
 * Sevalla's Pretty URLs feature 301-redirects bare paths to the trailing-
 * slash variant). Keeping every emitted URL aligned with that canonical
 * form avoids contradictory signals across `<link rel="canonical">`,
 * `sitemap.xml`, and JSON-LD breadcrumbs.
 */
export function buildCanonicalDocsUrl(slugs: string[] | undefined): string {
  if (!slugs?.length) return `${DOCS_SITE_ORIGIN}/`;
  const path = slugs.map((s) => encodeURIComponent(s)).join('/');
  return `${DOCS_SITE_ORIGIN}/${path}/`;
}

/**
 * Build the value to put in `<link rel="canonical">` for a docs page.
 *
 * For archived pages in sections whose back-versions are hidden from
 * indexing (currently the API summary), this returns the URL of the
 * section's **latest** (the bare basePath) — so search engines consolidate
 * authority on `/reference/api/` instead of treating each
 * `/reference/api/vX.Y.Z/` snapshot as its own canonical document. The HTML
 * page also carries `<meta robots="noindex">` (set in `page.tsx`), so the
 * canonical + noindex pair is the textbook "this is a near-duplicate,
 * prefer the canonical" signal.
 *
 * For every other page — including archived release-notes, which stay
 * indexed as standalone historical documents — this returns the page's own
 * self-URL.
 *
 * Always returns URLs **with a trailing slash** (see `buildCanonicalDocsUrl`
 * for the rationale).
 *
 * @see https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls
 */
export function buildPageCanonicalUrl(slugs: string[] | undefined): string {
  if (!slugs?.length) return `${DOCS_SITE_ORIGIN}/`;
  const url = '/' + slugs.join('/');
  const hiddenSection = HIDDEN_ARCHIVED_PAGE_TO_SECTION.get(url);
  if (hiddenSection) {
    return `${DOCS_SITE_ORIGIN}${hiddenSection.basePath}/`;
  }
  return buildCanonicalDocsUrl(slugs);
}

// Re-export to make the symbol available to tests / future helpers without
// reaching directly into `versions.ts`. Kept in this file because it's
// conceptually paired with `SECTIONS_HIDDEN_FROM_INDEXING`.
export { SECTIONS_HIDDEN_FROM_INDEXING, SECTIONS_KEPT_INDEXED };
