/**
 * Section-scoped version manifest. Only the API summary and the release
 * notes are versioned in the docs site — everything else (about-qvac,
 * getting-started, examples, tutorials, addons, cli, http-server) lives at
 * a single bare path that always reflects the current SDK.
 *
 * Each section is a single content folder under `content/docs/<basePath>/`:
 *   - The latest minor series is served from `index.mdx` at the bare
 *     basePath.
 *   - Older minor series are served from `<basePath>/v<X.Y>.x` via a
 *     sibling MDX file (`v<X.Y>.x.mdx`, literal "x"). The sibling
 *     accumulates patch sections (`## vX.Y.Z`) for that minor line.
 *
 * Auto-generated by `scripts/update-versions-list.ts` — do not edit by
 * hand for routine releases.
 */

export interface VersionEntry {
  label: string;
  value: string;
  isLatest?: boolean;
}

export interface VersionedSection {
  basePath: string;
  /**
   * Precise current patch (e.g. `v0.11.3`). Used by page renderers to
   * advertise the latest-patch number in titles / description ranges.
   * Not used for URL routing — that goes through `latestSeries`.
   */
  latest: string;
  /**
   * Series form of the current latest minor (e.g. `v0.11.x`). This is
   * the URL slug + version-selector value of the (latest) entry, and
   * the path `index.mdx` is served from at the bare `basePath`.
   */
  latestSeries: string;
  versions: VersionEntry[];
}

export const API_SECTION: VersionedSection = {
  basePath: '/reference/api',
  latest: 'v0.12.0',
  latestSeries: 'v0.12.x',
  versions: [
    { label: 'v0.12.x (latest)', value: 'v0.12.x', isLatest: true },
    { label: 'v0.11.x', value: 'v0.11.x' },
    { label: 'v0.10.x', value: 'v0.10.x' },
    { label: 'v0.9.x', value: 'v0.9.x' },
    { label: 'v0.8.x', value: 'v0.8.x' },
  ],
};

export const RELEASE_NOTES_SECTION: VersionedSection = {
  basePath: '/reference/release-notes',
  latest: 'v0.12.0',
  latestSeries: 'v0.12.x',
  versions: [
    { label: 'v0.12.x (latest)', value: 'v0.12.x', isLatest: true },
    { label: 'v0.11.x', value: 'v0.11.x' },
    { label: 'v0.10.x', value: 'v0.10.x' },
    { label: 'v0.9.x', value: 'v0.9.x' },
    { label: 'v0.8.x', value: 'v0.8.x' },
  ],
};

const VERSIONED_SECTIONS: VersionedSection[] = [
  API_SECTION,
  RELEASE_NOTES_SECTION,
];

/**
 * Re-exported for backward compatibility with consumers that advertise the
 * latest SDK version in plain text (e.g. the `llms.txt` route). Carries
 * the precise patch number, not the series.
 */
export const LATEST_VERSION = API_SECTION.latest;

/**
 * Return the versioned section the given pathname falls under, or `null`
 * when the pathname is not within any versioned section.
 */
export function getVersionedSection(
  pathname: string,
): VersionedSection | null {
  const normalized = pathname.replace(/\/+$/, '') || '/';
  return (
    VERSIONED_SECTIONS.find(
      (section) =>
        normalized === section.basePath ||
        normalized.startsWith(section.basePath + '/'),
    ) ?? null
  );
}

/**
 * Extract the current series slug from a versioned-section pathname.
 * Returns `section.latestSeries` when on the bare `basePath`
 * (`index.mdx` — the current latest minor series).
 */
export function getCurrentVersion(
  pathname: string,
  section: VersionedSection,
): string {
  const tail = pathname
    .slice(section.basePath.length)
    .replace(/^\/+|\/+$/g, '');
  if (!tail) return section.latestSeries;
  return tail.split('/')[0];
}

/**
 * Build the URL to navigate to when the user picks a target series inside
 * a section. The current latest series maps to `basePath/`; any other
 * series maps to `basePath/<value>/`.
 *
 * Trailing slash is mandatory: these URLs are consumed by the browser-side
 * version selector, and archived series slugs contain dots (`v0.8.x`).
 * Sevalla's Pretty URLs treats a bare dotted final segment as a file
 * request and 404s it before `_redirects` runs, so the bare→with-slash
 * normalization never fires for them. Emitting the trailing-slash form
 * directly lands on the `200` rewrite (see `public/_redirects`).
 */
export function computeSectionVersionUrl(
  section: VersionedSection,
  targetVersion: string,
): string {
  if (targetVersion === section.latestSeries) return `${section.basePath}/`;
  return `${section.basePath}/${targetVersion}/`;
}

/**
 * Props consumed by the client-side `<VersionSelector>` popover. All values
 * are precomputed at build time from the page slug so the client component
 * can stay a pure presentation layer (no `usePathname()`, no version-list
 * lookups in the browser).
 */
export interface VersionSelectorProps {
  versions: VersionEntry[];
  currentVersion: string;
  currentLabel: string;
  /**
   * Map of version `value` → absolute URL the user should land on when
   * picking that version. Keyed by `version.value` to avoid recomputing
   * `computeSectionVersionUrl` in the browser.
   */
  versionUrls: Record<string, string>;
}

/**
 * Compute the props for `<VersionSelector>` from a static page slug. Returns
 * `null` when the slug is not inside a versioned section so the page can
 * skip rendering (and importing) the component entirely.
 */
export function getVersionSelectorProps(
  slug: readonly string[],
): VersionSelectorProps | null {
  const pathname = `/${slug.join('/')}`;
  const section = getVersionedSection(pathname);
  if (!section) return null;

  const currentVersion = getCurrentVersion(pathname, section);
  const currentLabel =
    section.versions.find((v) => v.value === currentVersion)?.label ??
    currentVersion;

  const versionUrls: Record<string, string> = {};
  for (const version of section.versions) {
    versionUrls[version.value] = computeSectionVersionUrl(section, version.value);
  }

  return {
    versions: section.versions,
    currentVersion,
    currentLabel,
    versionUrls,
  };
}
