name: Approval Check Worker

on:
  pull_request_review:
    types: [submitted]
    
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write

    outputs:
      number: ${{ steps.pr.outputs.number }}
      sha: ${{ steps.pr.outputs.sha }}

    steps:
      - name: Get Pull Request Number
        id: pr
        run: |
          echo "number=$(gh pr view --json number -q .number)" >> $GITHUB_OUTPUT
          echo "number=$(gh pr view --json number -q .sha)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-approvals:
    needs: approved
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "number: ${{ needs.approved.outputs.number }}"
          echo "sha: ${{ needs.approved.outputs.sha }}"
