name: Integration Tests (Decoder-audio)

on:
  workflow_call:
    inputs:
      ref:
        description: "ref"
        type: string
      repository:
        type: string
      workdir:
        description: "Working directory inside the repo (monorepo package path)"
        type: string
        required: false
        default: "packages/decoder-audio"





jobs:
  runner_names:
    uses: ./.github/workflows/reusable-runner-names.yml

  run-integration-tests:
    needs: runner_names
    runs-on: ${{ matrix.runner || matrix.os }}
    environment: release
    name: test-${{ matrix.platform }}-${{ matrix.arch }}
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ${{ needs.runner_names.outputs.u22 }}
            platform: linux
            arch: x64
            runner: ${{ needs.runner_names.outputs.qvac_u22_GPU }}
          - os: ${{ needs.runner_names.outputs.u24 }}
            platform: linux
            arch: x64
            runner: ${{ needs.runner_names.outputs.qvac_u24_GPU }}
          - os: ${{ needs.runner_names.outputs.u24_ARM }}
            platform: linux
            arch: arm64
          - os: ${{ needs.runner_names.outputs.mac15_LG }}
            platform: darwin
            arch: x64
          - os: ${{ needs.runner_names.outputs.mac14 }}
            platform: darwin
            arch: arm64
          - os: ${{ needs.runner_names.outputs.win25 }}
            platform: win32
            arch: x64
            runner: ${{ needs.runner_names.outputs.qvac_win25_GPU }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: lts/*
      - name: Manual Workspace Cleanup
        run: rm -rf "$GITHUB_WORKSPACE" && mkdir -p "$GITHUB_WORKSPACE"
        shell: bash
        working-directory: .
        if: runner.environment != 'github-hosted'

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.ref }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install NPM dependencies
        working-directory: ${{ inputs.workdir }}
        run: |
          npm install

      - name: Install bare tooling
        run: npm install -g --force bare bare-make

      - name: Run integration test
        working-directory: ${{ inputs.workdir }}
        timeout-minutes: 10
        run: npm run test:integration
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
