name: On Merge to Main (Qvac-lib-infer-nmtcpp)

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "packages/qvac-lib-infer-nmtcpp/**"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish with"
        required: false
        default: ""
        type: string

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  prebuild:
    uses: ./.github/workflows/prebuilds-qvac-lib-infer-nmtcpp.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}

  model-conversion-test:
    needs: [prebuild]
    uses: ./.github/workflows/model-conversion-test-qvac-lib-infer-nmtcpp.yml
    secrets: inherit

  run-integration-tests:
    needs: [prebuild]
    uses: ./.github/workflows/integration-test-qvac-lib-infer-nmtcpp.yml
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
