name: On Merge Trigger (qvac-lib-infer-llamacpp-embed)

on:
  push:
    branches:
      - main 
    paths:
      - "packages/qvac-lib-infer-llamacpp-embed/**"    
permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  build-and-publish:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/prebuilds-qvac-lib-infer-llamacpp-embed.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag || 'latest' }}
      publish_target: 'npm'

  publish-release:
    needs: build-and-publish
    if: needs.build-and-publish.result == 'success' && needs.build-and-publish.outputs.published_version != ''
    permissions:
      contents: write
    uses: ./.github/workflows/create-github-release-qvac-lib-infer-llamacpp-embed.yml
    secrets: inherit
    with:
      published_version: ${{ needs.build-and-publish.outputs.published_version }}
      prev_sha: ${{ github.event.before }}
