name: On Merge to Main (Qvac-lib-infer-onnx-tts)

on:
  push:
    branches:
      - main
    paths:
      - "packages/qvac-lib-infer-onnx-tts/**"

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  prebuild:
    uses: ./.github/workflows/prebuilds-qvac-lib-infer-onnx-tts.yml
    secrets: inherit
    with:
      publish_target: "npm"
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}

  run-integration-tests:
    needs: prebuild
    uses: ./.github/workflows/integration-test-qvac-lib-infer-onnx-tts.yml
    secrets: inherit
