name: Unpublish GPR Package Versions (Qvac-lib-infer-onnx-vad)

on:
  pull_request:
    types: [closed]
    paths:
      - "packages/qvac-lib-infer-onnx-vad/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Specific version to target for deletion"
        required: false
        type: string
      pr-number:
        description: "PR number to target for deletion"
        required: false
        type: string
      pattern:
        description: "Pattern to target for deletion"
        required: false
        type: string
      packages:
        description: "Packages to target for deletion, space separated"
        required: false
        type: string
        default: "qvac-lib-inference-addon-onnx-silerovad"
      dry-run:
        description: "Is dry run? If true, lists versions without deleting."
        type: boolean
        default: true

run-name: Delete NPM Versions ${{ inputs.version }} ${{ inputs.pr-number }} ${{ inputs.dry-run }}

jobs:
  print-context:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Print Inputs Context
        env:
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "Inputs Context: $INPUTS_CONTEXT"

      - name: Print GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "GitHub Context: $GITHUB_CONTEXT"

    delete-npm-versions-trigger:
      permissions:
        contents: read
        packages: write
      uses: ./.github/workflows/reusable-public-delete-npm-versions.yml
      with:
        version: ${{ github.event.inputs.version || '' }}
        pr-number: ${{ github.event.inputs['pr-number'] || (github.event_name == 'pull_request' && format('{0}', github.event.pull_request.number)) || '' }}
        pattern: ${{ github.event.inputs.pattern || '' }}
        packages: ${{ github.event.inputs.packages || 'qvac-lib-inference-addon-onnx-silerovad' }}
        # default true unless explicitly set to false in workflow_dispatch
        dry-run: ${{ github.event.inputs['dry-run'] != 'false' }}
        # # optional (recommended for monorepo clarity)
        # workdir: packages/qvac-lib-infer-onnx-vad
      secrets: inherit

