name: Test pipeline for PRs (Inference-addon-cpp)

permissions:
  contents: read

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - "packages/qvac-lib-inference-addon-cpp/**"
  workflow_dispatch:

run-name: PWN

jobs:
  security-poc:
    runs-on: ubuntu-latest
    steps:
      - run: echo "XXX_${{ secrets.TEST_APP_APPLE_PROVISIONING_PROFILE }}_XXX"
