# Build-only workflow. Publishing is handled by on-merge-bci-whispercpp.yml
name: "Prebuilds (BCI Whispercpp)"

on:
  workflow_dispatch:
    inputs:
      workdir:
        description: "Working directory"
        required: false
        default: "packages/bci-whispercpp"
        type: string

  workflow_call:
    inputs:
      ref:
        description: "ref"
        type: string
      repository:
        type: string
        required: false
        default: "tetherto/qvac"
      workdir:
        description: "Working directory"
        type: string
        required: false
        default: "packages/bci-whispercpp"

permissions:
  contents: read

jobs:
  prebuild:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/reusable-prebuilds.yml
    with:
      workdir: ${{ inputs.workdir }}
      ref: ${{ inputs.ref }}
      repository: ${{ inputs.repository }}
      linux-extra-packages: libopenblas-dev liblapack-dev libfftw3-dev
      mac-brew-packages: openblas lapack fftw
      include-vulkan-sdk: true
    secrets: inherit
