name: General CI/CD (Qvac-lib-infer-base)
# This workflow is used to call the reusable workflows in the qvac-devops repository
# https://github.com/tetherto/qvac-devops/blob/production-workflows-tag/.github/workflows/public-reusable.yml

permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
      - release-*
      - feature-*
      - tmp-*
    paths:
      - "packages/qvac-lib-infer-base/**"
  workflow_dispatch:
    inputs:
      custom_input_1:
        required: false
        type: string
      custom_input_2:
        required: false
        type: string
      custom_input_3:
        required: false
        type: string

jobs:
  publish-main-gpr-dev:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish to GitHub Packages (dev)
        uses: tetherto/qvac-devops/.github/actions/publish-library-to-gpr@monorepo_update
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          tag: "dev"
          path: packages/qvac-lib-infer-base

  publish-release-npm:
    if: (github.event_name == 'push' && startsWith(github.ref_name, 'release-')) || (github.event_name == 'workflow_dispatch' && startsWith(github.ref_name, 'release-'))
    uses: tetherto/qvac-devops/.github/workflows/public-reusable-npm.yml@monorepo_update
    secrets: inherit
    with:
      workdir: packages/qvac-lib-infer-base

  publish-feature-gpr:
    if: (github.event_name == 'push' && startsWith(github.ref_name, 'feature-')) || (github.event_name == 'workflow_dispatch' && startsWith(github.ref_name, 'feature-'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish to GitHub Packages (feature)
        uses: tetherto/qvac-devops/.github/actions/publish-library-to-gpr@monorepo_update
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          tag: "feature"
          path: packages/qvac-lib-infer-base

  publish-tmp-gpr:
    if: (github.event_name == 'push' && startsWith(github.ref_name, 'tmp-')) || (github.event_name == 'workflow_dispatch' && startsWith(github.ref_name, 'tmp-'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish to GitHub Packages (tmp)
        uses: tetherto/qvac-devops/.github/actions/publish-library-to-gpr@monorepo_update
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          tag: "tmp"
          path: packages/qvac-lib-infer-base
