name: General CI/CD Qvac-CLI
# This workflow is used to call the reusable workflows in the qvac-devops repository
# (ported into the monorepo)

permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write

on:
  push:
    branches: [main]
    paths:
      - "packages/qvac-cli/**"
      - ".github/workflows/trigger-reusable-lib-qvac-cli.yml"

  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
    paths:
      - "packages/qvac-cli/**"
      - ".github/workflows/trigger-reusable-lib-qvac-cli.yml"

  workflow_dispatch:
    inputs:
      custom_input_1:
        required: false
        type: string
      custom_input_2:
        required: false
        type: string
      custom_input_3:
        required: false
        type: string

jobs:
  call-devops-lib:
    uses: ./.github/workflows/reusable-public-reusable.yml
    secrets: inherit
    with:
      workdir: packages/qvac-cli
